//! gizza-ai/spell-check core — detect misspelled English words and suggest
//! corrections, purely in Rust (no ML model, no network).
//!
//! How it works:
//! - A bundled dictionary of ~84k common English words (frequency-ordered from a
//!   subtitle corpus, augmented with a standard system word list) is embedded via
//!   `include_str!`. Membership = "spelled correctly"; a word's position gives a
//!   frequency-rank used to rank suggestions (more common words rank first).
//! - Unknown words get candidate corrections generated by Damerau-Levenshtein
//!   edits (deletes, transposes, replaces, inserts) at edit distance 1, then
//!   distance 2 if nothing is found at distance 1 — the classic Norvig approach.
//! - Candidates are filtered to real dictionary words and ranked by edit distance
//!   then frequency, so the most likely correction comes first.
//!
//! Limitations (stated on the page too): English, ASCII a–z only; it flags
//! spelling, not grammar; it cannot catch a real-word error (a correctly spelled
//! word used in the wrong place, e.g. "their" vs "there") — that needs a language
//! model and is out of scope here.

use std::collections::{HashMap, HashSet};
use std::sync::OnceLock;

use serde::Serialize;

/// Frequency-ordered, cleaned English word list (one lowercase word per line).
const WORDS: &str = include_str!("words.txt");

/// Word -> frequency rank (0 = most common). Lower rank ranks first in suggestions.
fn dict() -> &'static HashMap<&'static str, u32> {
    static DICT: OnceLock<HashMap<&'static str, u32>> = OnceLock::new();
    DICT.get_or_init(|| {
        let mut m = HashMap::with_capacity(90_000);
        for (i, line) in WORDS.lines().enumerate() {
            let w = line.trim();
            if !w.is_empty() {
                m.entry(w).or_insert(i as u32);
            }
        }
        m
    })
}

#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct Misspelling {
    /// The misspelled word exactly as it appears in the text.
    pub word: String,
    /// Zero-based character offset of the word's first character in the text.
    pub offset: usize,
    /// Ranked correction suggestions (best first); empty if none were found.
    pub suggestions: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct Report {
    /// One entry per misspelled occurrence, in reading order.
    pub misspelled: Vec<Misspelling>,
    /// Number of misspelled occurrences (= `misspelled.len()`).
    pub misspelled_count: usize,
    /// Number of word tokens that were checked (length ≥ 2, no digits).
    pub words_checked: usize,
    /// The input with each misspelling replaced by its top suggestion (casing
    /// preserved); words with no suggestion are left unchanged.
    pub corrected: String,
}

/// Byte spans of word tokens: runs of letters/digits with interior apostrophes
/// ("don't" stays one token); everything else separates.
fn tokenize(text: &str) -> Vec<(usize, usize)> {
    let chars: Vec<(usize, char)> = text.char_indices().collect();
    let mut out = Vec::new();
    let mut start: Option<usize> = None;
    let mut end = 0usize;
    for (idx, (i, c)) in chars.iter().enumerate() {
        let is_apos = *c == '\'' || *c == '\u{2019}';
        let next_is_word = chars
            .get(idx + 1)
            .map(|(_, nc)| nc.is_alphanumeric())
            .unwrap_or(false);
        let in_word = c.is_alphanumeric() || (is_apos && start.is_some() && next_is_word);
        if in_word {
            if start.is_none() {
                start = Some(*i);
            }
            end = i + c.len_utf8();
        } else if let Some(s) = start.take() {
            out.push((s, end));
        }
    }
    if let Some(s) = start {
        out.push((s, end));
    }
    out
}

fn is_all_upper(w: &str) -> bool {
    let mut saw_letter = false;
    for c in w.chars() {
        if c.is_alphabetic() {
            saw_letter = true;
            if !c.is_uppercase() {
                return false;
            }
        }
    }
    saw_letter
}

fn first_is_upper(w: &str) -> bool {
    w.chars()
        .find(|c| c.is_alphabetic())
        .map(|c| c.is_uppercase())
        .unwrap_or(false)
}

/// Re-apply the original word's casing to a lowercase suggestion.
fn recase(orig: &str, suggestion: &str) -> String {
    if is_all_upper(orig) && orig.chars().filter(|c| c.is_alphabetic()).count() > 1 {
        suggestion.to_uppercase()
    } else if first_is_upper(orig) {
        let mut cs = suggestion.chars();
        match cs.next() {
            Some(f) => f.to_uppercase().collect::<String>() + cs.as_str(),
            None => String::new(),
        }
    } else {
        suggestion.to_string()
    }
}

/// All strings one Damerau-Levenshtein edit away from `word` (delete, transpose,
/// replace, insert over a–z).
fn edits1(word: &[char]) -> HashSet<String> {
    const ALPHABET: &[u8] = b"abcdefghijklmnopqrstuvwxyz";
    let n = word.len();
    let mut res = HashSet::new();
    for i in 0..=n {
        let left = &word[..i];
        let right = &word[i..];
        // delete
        if !right.is_empty() {
            let mut s: String = left.iter().collect();
            s.extend(right[1..].iter());
            res.insert(s);
        }
        // transpose
        if right.len() > 1 {
            let mut s: String = left.iter().collect();
            s.push(right[1]);
            s.push(right[0]);
            s.extend(right[2..].iter());
            res.insert(s);
        }
        // replace
        if !right.is_empty() {
            for &b in ALPHABET {
                let mut s: String = left.iter().collect();
                s.push(b as char);
                s.extend(right[1..].iter());
                res.insert(s);
            }
        }
        // insert
        for &b in ALPHABET {
            let mut s: String = left.iter().collect();
            s.push(b as char);
            s.extend(right.iter());
            res.insert(s);
        }
    }
    res
}

/// Ranked correction suggestions for a lowercase word, best first, up to `max`.
fn suggest(lower: &str, max: usize) -> Vec<String> {
    if max == 0 {
        return Vec::new();
    }
    let d = dict();
    let chars: Vec<char> = lower.chars().collect();

    // distance-1 candidates
    let e1 = edits1(&chars);
    let mut hits: Vec<(u32, String)> = e1
        .iter()
        .filter(|w| w.as_str() != lower)
        .filter_map(|w| d.get(w.as_str()).map(|&r| (r, w.clone())))
        .collect();

    // distance-2 candidates only if distance-1 found nothing (bounded cost)
    if hits.is_empty() && chars.len() <= 15 {
        let mut seen: HashSet<String> = HashSet::new();
        for w in &e1 {
            for w2 in edits1(&w.chars().collect::<Vec<_>>()) {
                if w2 == lower || seen.contains(&w2) {
                    continue;
                }
                if let Some(&r) = d.get(w2.as_str()) {
                    seen.insert(w2.clone());
                    hits.push((r, w2));
                }
            }
        }
    }

    // rank by frequency (lower rank first), tie-break alphabetically
    hits.sort_by(|a, b| a.0.cmp(&b.0).then(a.1.cmp(&b.1)));
    hits.truncate(max);
    hits.into_iter().map(|(_, w)| w).collect()
}

/// True if a lowercase token is a well-formed English contraction whose stem is
/// a real word — the bundled dictionary holds no contractions, so `don't`,
/// `can't`, `it's`, `they're`, `we've`, `I'll`, `he'd`, `I'm` etc. are validated
/// by splitting off the enclitic and checking the stem. Handles the `n't` case
/// where the `n` may belong to the stem (`can't`→`can`) or the clitic
/// (`don't`→`do`, `isn't`→`is`).
fn contraction_ok(lower: &str, d: &HashMap<&'static str, u32>) -> bool {
    let mut parts = lower.splitn(2, |c: char| c == '\'' || c == '\u{2019}');
    let head = parts.next().unwrap_or("");
    let tail = match parts.next() {
        Some(t) => t,
        None => return false, // no apostrophe → not a contraction
    };
    if head.is_empty() || tail.is_empty() {
        return false;
    }
    match tail {
        "t" => {
            d.contains_key(head)
                || head
                    .strip_suffix('n')
                    .map(|s| !s.is_empty() && d.contains_key(s))
                    .unwrap_or(false)
        }
        "s" | "re" | "ve" | "ll" | "d" | "m" => d.contains_key(head),
        _ => false,
    }
}

fn parse_custom(custom_words: &str) -> HashSet<String> {
    custom_words
        .split(|c: char| !(c.is_alphanumeric() || c == '\'' || c == '\u{2019}'))
        .filter(|s| !s.is_empty())
        .map(|s| s.to_lowercase())
        .collect()
}

/// Check `text` for misspellings and build a full report.
///
/// - `max_suggestions`: correction suggestions per misspelled word (0 = none).
/// - `ignore_uppercase`: treat ALL-CAPS tokens (NASA, HTML) as correct.
/// - `ignore_capitalized`: treat Capitalized tokens (names/proper nouns) as correct.
/// - `custom_words`: extra words treated as correctly spelled.
pub fn check(
    text: &str,
    max_suggestions: usize,
    ignore_uppercase: bool,
    ignore_capitalized: bool,
    custom_words: &str,
) -> Report {
    let d = dict();
    let custom = parse_custom(custom_words);
    let mut misspelled: Vec<Misspelling> = Vec::new();
    let mut words_checked = 0usize;
    // memoize suggestions per distinct lowercase word
    let mut cache: HashMap<String, Vec<String>> = HashMap::new();

    // char offset of each byte start, for reporting positions
    let mut byte_to_char: HashMap<usize, usize> = HashMap::new();
    {
        let mut ci = 0usize;
        for (b, _) in text.char_indices() {
            byte_to_char.insert(b, ci);
            ci += 1;
        }
    }

    // Build corrected text alongside the scan.
    let mut corrected = String::with_capacity(text.len());
    let mut last = 0usize;

    for (bs, be) in tokenize(text) {
        let w = &text[bs..be];
        let char_len = w.chars().count();
        let has_digit = w.chars().any(|c| c.is_numeric());
        if char_len < 2 || has_digit {
            continue; // not a checkable word
        }
        words_checked += 1;

        let lower = w.to_lowercase();
        let correct = d.contains_key(lower.as_str())
            || custom.contains(&lower)
            || contraction_ok(&lower, d)
            || (ignore_uppercase && is_all_upper(w) && char_len > 1)
            || (ignore_capitalized && first_is_upper(w) && !is_all_upper(w));
        if correct {
            continue;
        }

        let sugg = cache
            .entry(lower.clone())
            .or_insert_with(|| suggest(&lower, max_suggestions))
            .clone();

        // append text up to the word, then the correction (or original)
        corrected.push_str(&text[last..bs]);
        if let Some(top) = sugg.first() {
            corrected.push_str(&recase(w, top));
        } else {
            corrected.push_str(w);
        }
        last = be;

        misspelled.push(Misspelling {
            word: w.to_string(),
            offset: *byte_to_char.get(&bs).unwrap_or(&0),
            suggestions: sugg.iter().map(|s| recase(w, s)).collect(),
        });
    }
    corrected.push_str(&text[last..]);

    let misspelled_count = misspelled.len();
    Report {
        misspelled,
        misspelled_count,
        words_checked,
        corrected,
    }
}

/// Human-readable report for the page/CLI. Misspellings are de-duplicated by
/// word (first casing kept) for a compact list; the corrected text is shown in full.
pub fn format_report(
    text: &str,
    max_suggestions: usize,
    ignore_uppercase: bool,
    ignore_capitalized: bool,
    custom_words: &str,
) -> String {
    let r = check(
        text,
        max_suggestions,
        ignore_uppercase,
        ignore_capitalized,
        custom_words,
    );
    if r.misspelled.is_empty() {
        return format!("No misspellings found ({} words checked).", r.words_checked);
    }

    let mut seen: HashSet<String> = HashSet::new();
    let mut lines: Vec<String> = Vec::new();
    for m in &r.misspelled {
        let key = m.word.to_lowercase();
        if !seen.insert(key) {
            continue;
        }
        if m.suggestions.is_empty() {
            lines.push(format!("{} → (no suggestions)", m.word));
        } else {
            lines.push(format!("{} → {}", m.word, m.suggestions.join(", ")));
        }
    }

    let noun = if r.misspelled_count == 1 {
        "misspelling"
    } else {
        "misspellings"
    };
    format!(
        "{} possible {} found ({} words checked):\n\n{}\n\nCorrected text:\n{}",
        r.misspelled_count,
        noun,
        r.words_checked,
        lines.join("\n"),
        r.corrected
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detects_and_suggests() {
        let r = check("I recieve", 5, true, false, "");
        assert_eq!(r.misspelled_count, 1);
        assert_eq!(r.words_checked, 1); // "I" is length 1 -> not checked
        assert_eq!(r.misspelled[0].word, "recieve");
        assert_eq!(r.misspelled[0].offset, 2);
        assert_eq!(r.misspelled[0].suggestions[0], "receive");
        assert_eq!(r.corrected, "I receive");
    }

    #[test]
    fn clean_text_has_no_misspellings() {
        let r = check("the quick brown fox", 5, true, false, "");
        assert_eq!(r.misspelled_count, 0);
        assert_eq!(r.words_checked, 4);
        assert!(r.misspelled.is_empty());
    }

    #[test]
    fn transposition_is_distance_one() {
        let r = check("teh", 3, true, false, "");
        assert_eq!(r.misspelled_count, 1);
        assert_eq!(r.misspelled[0].suggestions[0], "the");
    }

    #[test]
    fn preserves_capitalization_in_suggestion() {
        let r = check("Recieve", 3, true, false, "");
        assert_eq!(r.misspelled[0].suggestions[0], "Receive");
        assert_eq!(r.corrected, "Receive");
    }

    #[test]
    fn all_caps_treated_as_acronym_when_enabled() {
        // "ZZZQ" is not a word; with ignore_uppercase it is skipped.
        let on = check("ZZZQ", 3, true, false, "");
        assert_eq!(on.misspelled_count, 0);
        let off = check("ZZZQ", 3, false, false, "");
        assert_eq!(off.misspelled_count, 1);
    }

    #[test]
    fn custom_words_are_accepted() {
        let without = check("gizza", 3, true, false, "");
        assert_eq!(without.misspelled_count, 1);
        let with = check("gizza", 3, true, false, "gizza, wafer");
        assert_eq!(with.misspelled_count, 0);
    }

    #[test]
    fn ignore_capitalized_skips_proper_nouns() {
        let off = check("Zorbnak went home", 3, true, false, "");
        assert_eq!(off.misspelled_count, 1); // Zorbnak flagged
        let on = check("Zorbnak went home", 3, true, true, "");
        assert_eq!(on.misspelled_count, 0); // Zorbnak skipped as proper noun
    }

    #[test]
    fn digits_and_short_tokens_skipped() {
        let r = check("mp3 a I 42", 3, true, false, "");
        assert_eq!(r.words_checked, 0);
        assert_eq!(r.misspelled_count, 0);
    }

    #[test]
    fn keeps_interior_apostrophe() {
        let r = check("don't", 3, true, false, "");
        assert_eq!(r.misspelled_count, 0);
    }

    #[test]
    fn common_contractions_are_accepted() {
        // Stem-in-dict enclitics and both n't shapes (do+n't, can+n't).
        let r = check(
            "don't can't it's they're we've I'll he'd I'm doesn't wouldn't",
            3,
            true,
            false,
            "",
        );
        assert_eq!(r.misspelled_count, 0, "{:?}", r.misspelled);
    }

    #[test]
    fn bogus_contraction_is_flagged() {
        // "xyzq" is not a word, so "xyzq's" is not a valid contraction.
        let r = check("xyzq's", 3, true, false, "");
        assert_eq!(r.misspelled_count, 1);
    }

    #[test]
    fn no_suggestions_leaves_word_unchanged() {
        // A long random string has no distance-1/2 dictionary neighbor.
        let r = check("qwxzjkvbnm", 5, true, false, "");
        assert_eq!(r.misspelled_count, 1);
        assert!(r.misspelled[0].suggestions.is_empty());
        assert_eq!(r.corrected, "qwxzjkvbnm");
    }

    #[test]
    fn format_report_clean() {
        let t = format_report("the quick brown fox", 5, true, false, "");
        assert_eq!(t, "No misspellings found (4 words checked).");
    }

    #[test]
    fn format_report_with_errors() {
        let t = format_report("teh cat", 3, true, false, "");
        assert!(t.starts_with("1 possible misspelling found (2 words checked):"));
        assert!(t.contains("teh → the"));
        assert!(t.ends_with("Corrected text:\nthe cat"));
    }

    #[test]
    fn max_suggestions_caps_list() {
        let r = check("recieve", 2, true, false, "");
        assert!(r.misspelled[0].suggestions.len() <= 2);
        assert_eq!(r.misspelled[0].suggestions[0], "receive");
    }

    #[test]
    fn dictionary_loads_common_words() {
        let d = dict();
        assert!(d.contains_key("the"));
        assert!(d.contains_key("receive"));
        assert!(!d.contains_key("recieve"));
    }
}
