//! Generated ISO 3166-1 reference data — do NOT hand-edit.
//!
//! `COUNTRIES` is the ISO 3166-1 code list (English short name, alpha-2, alpha-3,
//! numeric) — factual standard data, cross-checked against the published list. `common`
//! is the everyday English name used by `name_style = "common"`; it equals `name`
//! wherever ISO's short name is already the everyday one.
//!
//! `ALIASES` maps an already-normalized lookup key (see `normalize_key`) to an alpha-2
//! code: former names, endonyms, abbreviations, UK constituent countries, and
//! unambiguous demonyms. Regenerate via the recipe in the crate docs rather than
//! editing entries by hand.

/// One ISO 3166-1 entry.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Country {
    /// ISO 3166-1 English short name (e.g. "Korea (Republic of)").
    pub name: &'static str,
    /// Everyday English name (e.g. "South Korea"); equals `name` when they agree.
    pub common: &'static str,
    /// ISO 3166-1 alpha-2 code.
    pub alpha2: &'static str,
    /// ISO 3166-1 alpha-3 code.
    pub alpha3: &'static str,
    /// ISO 3166-1 numeric code (1-894, not zero-padded).
    pub numeric: u16,
}

/// Every ISO 3166-1 officially assigned entry, in alpha-2 order.
pub const COUNTRIES: &[Country] = &[
    Country { name: "Andorra", common: "Andorra", alpha2: "AD", alpha3: "AND", numeric: 20 },
    Country { name: "United Arab Emirates", common: "United Arab Emirates", alpha2: "AE", alpha3: "ARE", numeric: 784 },
    Country { name: "Afghanistan", common: "Afghanistan", alpha2: "AF", alpha3: "AFG", numeric: 4 },
    Country { name: "Antigua and Barbuda", common: "Antigua and Barbuda", alpha2: "AG", alpha3: "ATG", numeric: 28 },
    Country { name: "Anguilla", common: "Anguilla", alpha2: "AI", alpha3: "AIA", numeric: 660 },
    Country { name: "Albania", common: "Albania", alpha2: "AL", alpha3: "ALB", numeric: 8 },
    Country { name: "Armenia", common: "Armenia", alpha2: "AM", alpha3: "ARM", numeric: 51 },
    Country { name: "Angola", common: "Angola", alpha2: "AO", alpha3: "AGO", numeric: 24 },
    Country { name: "Antarctica", common: "Antarctica", alpha2: "AQ", alpha3: "ATA", numeric: 10 },
    Country { name: "Argentina", common: "Argentina", alpha2: "AR", alpha3: "ARG", numeric: 32 },
    Country { name: "American Samoa", common: "American Samoa", alpha2: "AS", alpha3: "ASM", numeric: 16 },
    Country { name: "Austria", common: "Austria", alpha2: "AT", alpha3: "AUT", numeric: 40 },
    Country { name: "Australia", common: "Australia", alpha2: "AU", alpha3: "AUS", numeric: 36 },
    Country { name: "Aruba", common: "Aruba", alpha2: "AW", alpha3: "ABW", numeric: 533 },
    Country { name: "Åland Islands", common: "Åland Islands", alpha2: "AX", alpha3: "ALA", numeric: 248 },
    Country { name: "Azerbaijan", common: "Azerbaijan", alpha2: "AZ", alpha3: "AZE", numeric: 31 },
    Country { name: "Bosnia and Herzegovina", common: "Bosnia and Herzegovina", alpha2: "BA", alpha3: "BIH", numeric: 70 },
    Country { name: "Barbados", common: "Barbados", alpha2: "BB", alpha3: "BRB", numeric: 52 },
    Country { name: "Bangladesh", common: "Bangladesh", alpha2: "BD", alpha3: "BGD", numeric: 50 },
    Country { name: "Belgium", common: "Belgium", alpha2: "BE", alpha3: "BEL", numeric: 56 },
    Country { name: "Burkina Faso", common: "Burkina Faso", alpha2: "BF", alpha3: "BFA", numeric: 854 },
    Country { name: "Bulgaria", common: "Bulgaria", alpha2: "BG", alpha3: "BGR", numeric: 100 },
    Country { name: "Bahrain", common: "Bahrain", alpha2: "BH", alpha3: "BHR", numeric: 48 },
    Country { name: "Burundi", common: "Burundi", alpha2: "BI", alpha3: "BDI", numeric: 108 },
    Country { name: "Benin", common: "Benin", alpha2: "BJ", alpha3: "BEN", numeric: 204 },
    Country { name: "Saint Barthélemy", common: "Saint Barthélemy", alpha2: "BL", alpha3: "BLM", numeric: 652 },
    Country { name: "Bermuda", common: "Bermuda", alpha2: "BM", alpha3: "BMU", numeric: 60 },
    Country { name: "Brunei Darussalam", common: "Brunei", alpha2: "BN", alpha3: "BRN", numeric: 96 },
    Country { name: "Bolivia (Plurinational State of)", common: "Bolivia", alpha2: "BO", alpha3: "BOL", numeric: 68 },
    Country { name: "Bonaire, Sint Eustatius and Saba", common: "Caribbean Netherlands", alpha2: "BQ", alpha3: "BES", numeric: 535 },
    Country { name: "Brazil", common: "Brazil", alpha2: "BR", alpha3: "BRA", numeric: 76 },
    Country { name: "Bahamas", common: "Bahamas", alpha2: "BS", alpha3: "BHS", numeric: 44 },
    Country { name: "Bhutan", common: "Bhutan", alpha2: "BT", alpha3: "BTN", numeric: 64 },
    Country { name: "Bouvet Island", common: "Bouvet Island", alpha2: "BV", alpha3: "BVT", numeric: 74 },
    Country { name: "Botswana", common: "Botswana", alpha2: "BW", alpha3: "BWA", numeric: 72 },
    Country { name: "Belarus", common: "Belarus", alpha2: "BY", alpha3: "BLR", numeric: 112 },
    Country { name: "Belize", common: "Belize", alpha2: "BZ", alpha3: "BLZ", numeric: 84 },
    Country { name: "Canada", common: "Canada", alpha2: "CA", alpha3: "CAN", numeric: 124 },
    Country { name: "Cocos (Keeling) Islands", common: "Cocos Islands", alpha2: "CC", alpha3: "CCK", numeric: 166 },
    Country { name: "Congo (Democratic Republic of the)", common: "DR Congo", alpha2: "CD", alpha3: "COD", numeric: 180 },
    Country { name: "Central African Republic", common: "Central African Republic", alpha2: "CF", alpha3: "CAF", numeric: 140 },
    Country { name: "Congo", common: "Republic of the Congo", alpha2: "CG", alpha3: "COG", numeric: 178 },
    Country { name: "Switzerland", common: "Switzerland", alpha2: "CH", alpha3: "CHE", numeric: 756 },
    Country { name: "Côte d'Ivoire", common: "Ivory Coast", alpha2: "CI", alpha3: "CIV", numeric: 384 },
    Country { name: "Cook Islands", common: "Cook Islands", alpha2: "CK", alpha3: "COK", numeric: 184 },
    Country { name: "Chile", common: "Chile", alpha2: "CL", alpha3: "CHL", numeric: 152 },
    Country { name: "Cameroon", common: "Cameroon", alpha2: "CM", alpha3: "CMR", numeric: 120 },
    Country { name: "China", common: "China", alpha2: "CN", alpha3: "CHN", numeric: 156 },
    Country { name: "Colombia", common: "Colombia", alpha2: "CO", alpha3: "COL", numeric: 170 },
    Country { name: "Costa Rica", common: "Costa Rica", alpha2: "CR", alpha3: "CRI", numeric: 188 },
    Country { name: "Cuba", common: "Cuba", alpha2: "CU", alpha3: "CUB", numeric: 192 },
    Country { name: "Cabo Verde", common: "Cape Verde", alpha2: "CV", alpha3: "CPV", numeric: 132 },
    Country { name: "Curaçao", common: "Curaçao", alpha2: "CW", alpha3: "CUW", numeric: 531 },
    Country { name: "Christmas Island", common: "Christmas Island", alpha2: "CX", alpha3: "CXR", numeric: 162 },
    Country { name: "Cyprus", common: "Cyprus", alpha2: "CY", alpha3: "CYP", numeric: 196 },
    Country { name: "Czechia", common: "Czechia", alpha2: "CZ", alpha3: "CZE", numeric: 203 },
    Country { name: "Germany", common: "Germany", alpha2: "DE", alpha3: "DEU", numeric: 276 },
    Country { name: "Djibouti", common: "Djibouti", alpha2: "DJ", alpha3: "DJI", numeric: 262 },
    Country { name: "Denmark", common: "Denmark", alpha2: "DK", alpha3: "DNK", numeric: 208 },
    Country { name: "Dominica", common: "Dominica", alpha2: "DM", alpha3: "DMA", numeric: 212 },
    Country { name: "Dominican Republic", common: "Dominican Republic", alpha2: "DO", alpha3: "DOM", numeric: 214 },
    Country { name: "Algeria", common: "Algeria", alpha2: "DZ", alpha3: "DZA", numeric: 12 },
    Country { name: "Ecuador", common: "Ecuador", alpha2: "EC", alpha3: "ECU", numeric: 218 },
    Country { name: "Estonia", common: "Estonia", alpha2: "EE", alpha3: "EST", numeric: 233 },
    Country { name: "Egypt", common: "Egypt", alpha2: "EG", alpha3: "EGY", numeric: 818 },
    Country { name: "Western Sahara", common: "Western Sahara", alpha2: "EH", alpha3: "ESH", numeric: 732 },
    Country { name: "Eritrea", common: "Eritrea", alpha2: "ER", alpha3: "ERI", numeric: 232 },
    Country { name: "Spain", common: "Spain", alpha2: "ES", alpha3: "ESP", numeric: 724 },
    Country { name: "Ethiopia", common: "Ethiopia", alpha2: "ET", alpha3: "ETH", numeric: 231 },
    Country { name: "Finland", common: "Finland", alpha2: "FI", alpha3: "FIN", numeric: 246 },
    Country { name: "Fiji", common: "Fiji", alpha2: "FJ", alpha3: "FJI", numeric: 242 },
    Country { name: "Falkland Islands (Malvinas)", common: "Falkland Islands", alpha2: "FK", alpha3: "FLK", numeric: 238 },
    Country { name: "Micronesia (Federated States of)", common: "Micronesia", alpha2: "FM", alpha3: "FSM", numeric: 583 },
    Country { name: "Faroe Islands", common: "Faroe Islands", alpha2: "FO", alpha3: "FRO", numeric: 234 },
    Country { name: "France", common: "France", alpha2: "FR", alpha3: "FRA", numeric: 250 },
    Country { name: "Gabon", common: "Gabon", alpha2: "GA", alpha3: "GAB", numeric: 266 },
    Country { name: "United Kingdom of Great Britain and Northern Ireland", common: "United Kingdom", alpha2: "GB", alpha3: "GBR", numeric: 826 },
    Country { name: "Grenada", common: "Grenada", alpha2: "GD", alpha3: "GRD", numeric: 308 },
    Country { name: "Georgia", common: "Georgia", alpha2: "GE", alpha3: "GEO", numeric: 268 },
    Country { name: "French Guiana", common: "French Guiana", alpha2: "GF", alpha3: "GUF", numeric: 254 },
    Country { name: "Guernsey", common: "Guernsey", alpha2: "GG", alpha3: "GGY", numeric: 831 },
    Country { name: "Ghana", common: "Ghana", alpha2: "GH", alpha3: "GHA", numeric: 288 },
    Country { name: "Gibraltar", common: "Gibraltar", alpha2: "GI", alpha3: "GIB", numeric: 292 },
    Country { name: "Greenland", common: "Greenland", alpha2: "GL", alpha3: "GRL", numeric: 304 },
    Country { name: "Gambia", common: "Gambia", alpha2: "GM", alpha3: "GMB", numeric: 270 },
    Country { name: "Guinea", common: "Guinea", alpha2: "GN", alpha3: "GIN", numeric: 324 },
    Country { name: "Guadeloupe", common: "Guadeloupe", alpha2: "GP", alpha3: "GLP", numeric: 312 },
    Country { name: "Equatorial Guinea", common: "Equatorial Guinea", alpha2: "GQ", alpha3: "GNQ", numeric: 226 },
    Country { name: "Greece", common: "Greece", alpha2: "GR", alpha3: "GRC", numeric: 300 },
    Country { name: "South Georgia and the South Sandwich Islands", common: "South Georgia and the South Sandwich Islands", alpha2: "GS", alpha3: "SGS", numeric: 239 },
    Country { name: "Guatemala", common: "Guatemala", alpha2: "GT", alpha3: "GTM", numeric: 320 },
    Country { name: "Guam", common: "Guam", alpha2: "GU", alpha3: "GUM", numeric: 316 },
    Country { name: "Guinea-Bissau", common: "Guinea-Bissau", alpha2: "GW", alpha3: "GNB", numeric: 624 },
    Country { name: "Guyana", common: "Guyana", alpha2: "GY", alpha3: "GUY", numeric: 328 },
    Country { name: "Hong Kong", common: "Hong Kong", alpha2: "HK", alpha3: "HKG", numeric: 344 },
    Country { name: "Heard Island and McDonald Islands", common: "Heard Island and McDonald Islands", alpha2: "HM", alpha3: "HMD", numeric: 334 },
    Country { name: "Honduras", common: "Honduras", alpha2: "HN", alpha3: "HND", numeric: 340 },
    Country { name: "Croatia", common: "Croatia", alpha2: "HR", alpha3: "HRV", numeric: 191 },
    Country { name: "Haiti", common: "Haiti", alpha2: "HT", alpha3: "HTI", numeric: 332 },
    Country { name: "Hungary", common: "Hungary", alpha2: "HU", alpha3: "HUN", numeric: 348 },
    Country { name: "Indonesia", common: "Indonesia", alpha2: "ID", alpha3: "IDN", numeric: 360 },
    Country { name: "Ireland", common: "Ireland", alpha2: "IE", alpha3: "IRL", numeric: 372 },
    Country { name: "Israel", common: "Israel", alpha2: "IL", alpha3: "ISR", numeric: 376 },
    Country { name: "Isle of Man", common: "Isle of Man", alpha2: "IM", alpha3: "IMN", numeric: 833 },
    Country { name: "India", common: "India", alpha2: "IN", alpha3: "IND", numeric: 356 },
    Country { name: "British Indian Ocean Territory", common: "British Indian Ocean Territory", alpha2: "IO", alpha3: "IOT", numeric: 86 },
    Country { name: "Iraq", common: "Iraq", alpha2: "IQ", alpha3: "IRQ", numeric: 368 },
    Country { name: "Iran (Islamic Republic of)", common: "Iran", alpha2: "IR", alpha3: "IRN", numeric: 364 },
    Country { name: "Iceland", common: "Iceland", alpha2: "IS", alpha3: "ISL", numeric: 352 },
    Country { name: "Italy", common: "Italy", alpha2: "IT", alpha3: "ITA", numeric: 380 },
    Country { name: "Jersey", common: "Jersey", alpha2: "JE", alpha3: "JEY", numeric: 832 },
    Country { name: "Jamaica", common: "Jamaica", alpha2: "JM", alpha3: "JAM", numeric: 388 },
    Country { name: "Jordan", common: "Jordan", alpha2: "JO", alpha3: "JOR", numeric: 400 },
    Country { name: "Japan", common: "Japan", alpha2: "JP", alpha3: "JPN", numeric: 392 },
    Country { name: "Kenya", common: "Kenya", alpha2: "KE", alpha3: "KEN", numeric: 404 },
    Country { name: "Kyrgyzstan", common: "Kyrgyzstan", alpha2: "KG", alpha3: "KGZ", numeric: 417 },
    Country { name: "Cambodia", common: "Cambodia", alpha2: "KH", alpha3: "KHM", numeric: 116 },
    Country { name: "Kiribati", common: "Kiribati", alpha2: "KI", alpha3: "KIR", numeric: 296 },
    Country { name: "Comoros", common: "Comoros", alpha2: "KM", alpha3: "COM", numeric: 174 },
    Country { name: "Saint Kitts and Nevis", common: "Saint Kitts and Nevis", alpha2: "KN", alpha3: "KNA", numeric: 659 },
    Country { name: "Korea (Democratic People's Republic of)", common: "North Korea", alpha2: "KP", alpha3: "PRK", numeric: 408 },
    Country { name: "Korea (Republic of)", common: "South Korea", alpha2: "KR", alpha3: "KOR", numeric: 410 },
    Country { name: "Kuwait", common: "Kuwait", alpha2: "KW", alpha3: "KWT", numeric: 414 },
    Country { name: "Cayman Islands", common: "Cayman Islands", alpha2: "KY", alpha3: "CYM", numeric: 136 },
    Country { name: "Kazakhstan", common: "Kazakhstan", alpha2: "KZ", alpha3: "KAZ", numeric: 398 },
    Country { name: "Lao People's Democratic Republic", common: "Laos", alpha2: "LA", alpha3: "LAO", numeric: 418 },
    Country { name: "Lebanon", common: "Lebanon", alpha2: "LB", alpha3: "LBN", numeric: 422 },
    Country { name: "Saint Lucia", common: "Saint Lucia", alpha2: "LC", alpha3: "LCA", numeric: 662 },
    Country { name: "Liechtenstein", common: "Liechtenstein", alpha2: "LI", alpha3: "LIE", numeric: 438 },
    Country { name: "Sri Lanka", common: "Sri Lanka", alpha2: "LK", alpha3: "LKA", numeric: 144 },
    Country { name: "Liberia", common: "Liberia", alpha2: "LR", alpha3: "LBR", numeric: 430 },
    Country { name: "Lesotho", common: "Lesotho", alpha2: "LS", alpha3: "LSO", numeric: 426 },
    Country { name: "Lithuania", common: "Lithuania", alpha2: "LT", alpha3: "LTU", numeric: 440 },
    Country { name: "Luxembourg", common: "Luxembourg", alpha2: "LU", alpha3: "LUX", numeric: 442 },
    Country { name: "Latvia", common: "Latvia", alpha2: "LV", alpha3: "LVA", numeric: 428 },
    Country { name: "Libya", common: "Libya", alpha2: "LY", alpha3: "LBY", numeric: 434 },
    Country { name: "Morocco", common: "Morocco", alpha2: "MA", alpha3: "MAR", numeric: 504 },
    Country { name: "Monaco", common: "Monaco", alpha2: "MC", alpha3: "MCO", numeric: 492 },
    Country { name: "Moldova (Republic of)", common: "Moldova", alpha2: "MD", alpha3: "MDA", numeric: 498 },
    Country { name: "Montenegro", common: "Montenegro", alpha2: "ME", alpha3: "MNE", numeric: 499 },
    Country { name: "Saint Martin (French part)", common: "Saint Martin", alpha2: "MF", alpha3: "MAF", numeric: 663 },
    Country { name: "Madagascar", common: "Madagascar", alpha2: "MG", alpha3: "MDG", numeric: 450 },
    Country { name: "Marshall Islands", common: "Marshall Islands", alpha2: "MH", alpha3: "MHL", numeric: 584 },
    Country { name: "North Macedonia", common: "North Macedonia", alpha2: "MK", alpha3: "MKD", numeric: 807 },
    Country { name: "Mali", common: "Mali", alpha2: "ML", alpha3: "MLI", numeric: 466 },
    Country { name: "Myanmar", common: "Myanmar", alpha2: "MM", alpha3: "MMR", numeric: 104 },
    Country { name: "Mongolia", common: "Mongolia", alpha2: "MN", alpha3: "MNG", numeric: 496 },
    Country { name: "Macao", common: "Macau", alpha2: "MO", alpha3: "MAC", numeric: 446 },
    Country { name: "Northern Mariana Islands", common: "Northern Mariana Islands", alpha2: "MP", alpha3: "MNP", numeric: 580 },
    Country { name: "Martinique", common: "Martinique", alpha2: "MQ", alpha3: "MTQ", numeric: 474 },
    Country { name: "Mauritania", common: "Mauritania", alpha2: "MR", alpha3: "MRT", numeric: 478 },
    Country { name: "Montserrat", common: "Montserrat", alpha2: "MS", alpha3: "MSR", numeric: 500 },
    Country { name: "Malta", common: "Malta", alpha2: "MT", alpha3: "MLT", numeric: 470 },
    Country { name: "Mauritius", common: "Mauritius", alpha2: "MU", alpha3: "MUS", numeric: 480 },
    Country { name: "Maldives", common: "Maldives", alpha2: "MV", alpha3: "MDV", numeric: 462 },
    Country { name: "Malawi", common: "Malawi", alpha2: "MW", alpha3: "MWI", numeric: 454 },
    Country { name: "Mexico", common: "Mexico", alpha2: "MX", alpha3: "MEX", numeric: 484 },
    Country { name: "Malaysia", common: "Malaysia", alpha2: "MY", alpha3: "MYS", numeric: 458 },
    Country { name: "Mozambique", common: "Mozambique", alpha2: "MZ", alpha3: "MOZ", numeric: 508 },
    Country { name: "Namibia", common: "Namibia", alpha2: "NA", alpha3: "NAM", numeric: 516 },
    Country { name: "New Caledonia", common: "New Caledonia", alpha2: "NC", alpha3: "NCL", numeric: 540 },
    Country { name: "Niger", common: "Niger", alpha2: "NE", alpha3: "NER", numeric: 562 },
    Country { name: "Norfolk Island", common: "Norfolk Island", alpha2: "NF", alpha3: "NFK", numeric: 574 },
    Country { name: "Nigeria", common: "Nigeria", alpha2: "NG", alpha3: "NGA", numeric: 566 },
    Country { name: "Nicaragua", common: "Nicaragua", alpha2: "NI", alpha3: "NIC", numeric: 558 },
    Country { name: "Netherlands (Kingdom of the)", common: "Netherlands", alpha2: "NL", alpha3: "NLD", numeric: 528 },
    Country { name: "Norway", common: "Norway", alpha2: "NO", alpha3: "NOR", numeric: 578 },
    Country { name: "Nepal", common: "Nepal", alpha2: "NP", alpha3: "NPL", numeric: 524 },
    Country { name: "Nauru", common: "Nauru", alpha2: "NR", alpha3: "NRU", numeric: 520 },
    Country { name: "Niue", common: "Niue", alpha2: "NU", alpha3: "NIU", numeric: 570 },
    Country { name: "New Zealand", common: "New Zealand", alpha2: "NZ", alpha3: "NZL", numeric: 554 },
    Country { name: "Oman", common: "Oman", alpha2: "OM", alpha3: "OMN", numeric: 512 },
    Country { name: "Panama", common: "Panama", alpha2: "PA", alpha3: "PAN", numeric: 591 },
    Country { name: "Peru", common: "Peru", alpha2: "PE", alpha3: "PER", numeric: 604 },
    Country { name: "French Polynesia", common: "French Polynesia", alpha2: "PF", alpha3: "PYF", numeric: 258 },
    Country { name: "Papua New Guinea", common: "Papua New Guinea", alpha2: "PG", alpha3: "PNG", numeric: 598 },
    Country { name: "Philippines", common: "Philippines", alpha2: "PH", alpha3: "PHL", numeric: 608 },
    Country { name: "Pakistan", common: "Pakistan", alpha2: "PK", alpha3: "PAK", numeric: 586 },
    Country { name: "Poland", common: "Poland", alpha2: "PL", alpha3: "POL", numeric: 616 },
    Country { name: "Saint Pierre and Miquelon", common: "Saint Pierre and Miquelon", alpha2: "PM", alpha3: "SPM", numeric: 666 },
    Country { name: "Pitcairn", common: "Pitcairn", alpha2: "PN", alpha3: "PCN", numeric: 612 },
    Country { name: "Puerto Rico", common: "Puerto Rico", alpha2: "PR", alpha3: "PRI", numeric: 630 },
    Country { name: "Palestine (State of)", common: "Palestine", alpha2: "PS", alpha3: "PSE", numeric: 275 },
    Country { name: "Portugal", common: "Portugal", alpha2: "PT", alpha3: "PRT", numeric: 620 },
    Country { name: "Palau", common: "Palau", alpha2: "PW", alpha3: "PLW", numeric: 585 },
    Country { name: "Paraguay", common: "Paraguay", alpha2: "PY", alpha3: "PRY", numeric: 600 },
    Country { name: "Qatar", common: "Qatar", alpha2: "QA", alpha3: "QAT", numeric: 634 },
    Country { name: "Réunion", common: "Réunion", alpha2: "RE", alpha3: "REU", numeric: 638 },
    Country { name: "Romania", common: "Romania", alpha2: "RO", alpha3: "ROU", numeric: 642 },
    Country { name: "Serbia", common: "Serbia", alpha2: "RS", alpha3: "SRB", numeric: 688 },
    Country { name: "Russian Federation", common: "Russia", alpha2: "RU", alpha3: "RUS", numeric: 643 },
    Country { name: "Rwanda", common: "Rwanda", alpha2: "RW", alpha3: "RWA", numeric: 646 },
    Country { name: "Saudi Arabia", common: "Saudi Arabia", alpha2: "SA", alpha3: "SAU", numeric: 682 },
    Country { name: "Solomon Islands", common: "Solomon Islands", alpha2: "SB", alpha3: "SLB", numeric: 90 },
    Country { name: "Seychelles", common: "Seychelles", alpha2: "SC", alpha3: "SYC", numeric: 690 },
    Country { name: "Sudan", common: "Sudan", alpha2: "SD", alpha3: "SDN", numeric: 729 },
    Country { name: "Sweden", common: "Sweden", alpha2: "SE", alpha3: "SWE", numeric: 752 },
    Country { name: "Singapore", common: "Singapore", alpha2: "SG", alpha3: "SGP", numeric: 702 },
    Country { name: "Saint Helena, Ascension and Tristan da Cunha", common: "Saint Helena", alpha2: "SH", alpha3: "SHN", numeric: 654 },
    Country { name: "Slovenia", common: "Slovenia", alpha2: "SI", alpha3: "SVN", numeric: 705 },
    Country { name: "Svalbard and Jan Mayen", common: "Svalbard and Jan Mayen", alpha2: "SJ", alpha3: "SJM", numeric: 744 },
    Country { name: "Slovakia", common: "Slovakia", alpha2: "SK", alpha3: "SVK", numeric: 703 },
    Country { name: "Sierra Leone", common: "Sierra Leone", alpha2: "SL", alpha3: "SLE", numeric: 694 },
    Country { name: "San Marino", common: "San Marino", alpha2: "SM", alpha3: "SMR", numeric: 674 },
    Country { name: "Senegal", common: "Senegal", alpha2: "SN", alpha3: "SEN", numeric: 686 },
    Country { name: "Somalia", common: "Somalia", alpha2: "SO", alpha3: "SOM", numeric: 706 },
    Country { name: "Suriname", common: "Suriname", alpha2: "SR", alpha3: "SUR", numeric: 740 },
    Country { name: "South Sudan", common: "South Sudan", alpha2: "SS", alpha3: "SSD", numeric: 728 },
    Country { name: "Sao Tome and Principe", common: "Sao Tome and Principe", alpha2: "ST", alpha3: "STP", numeric: 678 },
    Country { name: "El Salvador", common: "El Salvador", alpha2: "SV", alpha3: "SLV", numeric: 222 },
    Country { name: "Sint Maarten (Dutch part)", common: "Sint Maarten", alpha2: "SX", alpha3: "SXM", numeric: 534 },
    Country { name: "Syrian Arab Republic", common: "Syria", alpha2: "SY", alpha3: "SYR", numeric: 760 },
    Country { name: "Eswatini", common: "Eswatini", alpha2: "SZ", alpha3: "SWZ", numeric: 748 },
    Country { name: "Turks and Caicos Islands", common: "Turks and Caicos Islands", alpha2: "TC", alpha3: "TCA", numeric: 796 },
    Country { name: "Chad", common: "Chad", alpha2: "TD", alpha3: "TCD", numeric: 148 },
    Country { name: "French Southern Territories", common: "French Southern Territories", alpha2: "TF", alpha3: "ATF", numeric: 260 },
    Country { name: "Togo", common: "Togo", alpha2: "TG", alpha3: "TGO", numeric: 768 },
    Country { name: "Thailand", common: "Thailand", alpha2: "TH", alpha3: "THA", numeric: 764 },
    Country { name: "Tajikistan", common: "Tajikistan", alpha2: "TJ", alpha3: "TJK", numeric: 762 },
    Country { name: "Tokelau", common: "Tokelau", alpha2: "TK", alpha3: "TKL", numeric: 772 },
    Country { name: "Timor-Leste", common: "East Timor", alpha2: "TL", alpha3: "TLS", numeric: 626 },
    Country { name: "Turkmenistan", common: "Turkmenistan", alpha2: "TM", alpha3: "TKM", numeric: 795 },
    Country { name: "Tunisia", common: "Tunisia", alpha2: "TN", alpha3: "TUN", numeric: 788 },
    Country { name: "Tonga", common: "Tonga", alpha2: "TO", alpha3: "TON", numeric: 776 },
    Country { name: "Türkiye", common: "Turkey", alpha2: "TR", alpha3: "TUR", numeric: 792 },
    Country { name: "Trinidad and Tobago", common: "Trinidad and Tobago", alpha2: "TT", alpha3: "TTO", numeric: 780 },
    Country { name: "Tuvalu", common: "Tuvalu", alpha2: "TV", alpha3: "TUV", numeric: 798 },
    Country { name: "Taiwan (Province of China)", common: "Taiwan", alpha2: "TW", alpha3: "TWN", numeric: 158 },
    Country { name: "Tanzania (United Republic of)", common: "Tanzania", alpha2: "TZ", alpha3: "TZA", numeric: 834 },
    Country { name: "Ukraine", common: "Ukraine", alpha2: "UA", alpha3: "UKR", numeric: 804 },
    Country { name: "Uganda", common: "Uganda", alpha2: "UG", alpha3: "UGA", numeric: 800 },
    Country { name: "United States Minor Outlying Islands", common: "United States Minor Outlying Islands", alpha2: "UM", alpha3: "UMI", numeric: 581 },
    Country { name: "United States of America", common: "United States", alpha2: "US", alpha3: "USA", numeric: 840 },
    Country { name: "Uruguay", common: "Uruguay", alpha2: "UY", alpha3: "URY", numeric: 858 },
    Country { name: "Uzbekistan", common: "Uzbekistan", alpha2: "UZ", alpha3: "UZB", numeric: 860 },
    Country { name: "Holy See", common: "Vatican City", alpha2: "VA", alpha3: "VAT", numeric: 336 },
    Country { name: "Saint Vincent and the Grenadines", common: "Saint Vincent and the Grenadines", alpha2: "VC", alpha3: "VCT", numeric: 670 },
    Country { name: "Venezuela (Bolivarian Republic of)", common: "Venezuela", alpha2: "VE", alpha3: "VEN", numeric: 862 },
    Country { name: "Virgin Islands (British)", common: "British Virgin Islands", alpha2: "VG", alpha3: "VGB", numeric: 92 },
    Country { name: "Virgin Islands (U.S.)", common: "U.S. Virgin Islands", alpha2: "VI", alpha3: "VIR", numeric: 850 },
    Country { name: "Viet Nam", common: "Vietnam", alpha2: "VN", alpha3: "VNM", numeric: 704 },
    Country { name: "Vanuatu", common: "Vanuatu", alpha2: "VU", alpha3: "VUT", numeric: 548 },
    Country { name: "Wallis and Futuna", common: "Wallis and Futuna", alpha2: "WF", alpha3: "WLF", numeric: 876 },
    Country { name: "Samoa", common: "Samoa", alpha2: "WS", alpha3: "WSM", numeric: 882 },
    Country { name: "Yemen", common: "Yemen", alpha2: "YE", alpha3: "YEM", numeric: 887 },
    Country { name: "Mayotte", common: "Mayotte", alpha2: "YT", alpha3: "MYT", numeric: 175 },
    Country { name: "South Africa", common: "South Africa", alpha2: "ZA", alpha3: "ZAF", numeric: 710 },
    Country { name: "Zambia", common: "Zambia", alpha2: "ZM", alpha3: "ZMB", numeric: 894 },
    Country { name: "Zimbabwe", common: "Zimbabwe", alpha2: "ZW", alpha3: "ZWE", numeric: 716 },
];

/// Normalized alias key -> alpha-2 code, sorted by key.
pub const ALIASES: &[(&str, &str)] = &[
    ("afghan", "AF"),
    ("aland", "AX"),
    ("america", "US"),
    ("american", "US"),
    ("americanvirginislands", "VI"),
    ("aotearoa", "NZ"),
    ("arabrepublicofegypt", "EG"),
    ("argentine", "AR"),
    ("argentinian", "AR"),
    ("australian", "AU"),
    ("austrian", "AT"),
    ("bangladeshi", "BD"),
    ("belgian", "BE"),
    ("belgie", "BE"),
    ("belgique", "BE"),
    ("belorussia", "BY"),
    ("bharat", "IN"),
    ("bolivia", "BO"),
    ("bosnia", "BA"),
    ("bosniaherzegovina", "BA"),
    ("brasil", "BR"),
    ("brazilian", "BR"),
    ("britain", "GB"),
    ("british", "GB"),
    ("britishvirginislands", "VG"),
    ("brunei", "BN"),
    ("bulgarian", "BG"),
    ("burma", "MM"),
    ("bvi", "VG"),
    ("byelorussia", "BY"),
    ("canadian", "CA"),
    ("capeverde", "CV"),
    ("caribbeannetherlands", "BQ"),
    ("ceylon", "LK"),
    ("chilean", "CL"),
    ("chinese", "CN"),
    ("chinesetaipei", "TW"),
    ("cocosislands", "CC"),
    ("colombian", "CO"),
    ("congobrazzaville", "CG"),
    ("congodemrep", "CD"),
    ("congokinshasa", "CD"),
    ("congorep", "CG"),
    ("croatian", "HR"),
    ("czech", "CZ"),
    ("czechrepublic", "CZ"),
    ("danish", "DK"),
    ("danmark", "DK"),
    ("democraticpeoplesrepublicofkorea", "KP"),
    ("democraticrepublicofcongo", "CD"),
    ("democraticrepublicofthecongo", "CD"),
    ("deutschland", "DE"),
    ("dominicanrep", "DO"),
    ("dprk", "KP"),
    ("drc", "CD"),
    ("drcongo", "CD"),
    ("dutch", "NL"),
    ("easttimor", "TL"),
    ("egyptarabrep", "EG"),
    ("egyptian", "EG"),
    ("eire", "IE"),
    ("emirates", "AE"),
    ("emirati", "AE"),
    ("england", "GB"),
    ("english", "GB"),
    ("espana", "ES"),
    ("falklands", "FK"),
    ("filipino", "PH"),
    ("finnish", "FI"),
    ("formeryugoslavrepublicofmacedonia", "MK"),
    ("french", "FR"),
    ("frg", "DE"),
    ("fyrom", "MK"),
    ("georgian", "GE"),
    ("german", "DE"),
    ("greatbritain", "GB"),
    ("greek", "GR"),
    ("hellas", "GR"),
    ("hellenicrepublic", "GR"),
    ("holland", "NL"),
    ("hongkongsar", "HK"),
    ("hrvatska", "HR"),
    ("hungarian", "HU"),
    ("icelandic", "IS"),
    ("indian", "IN"),
    ("indonesian", "ID"),
    ("iran", "IR"),
    ("iranian", "IR"),
    ("iraqi", "IQ"),
    ("irish", "IE"),
    ("islamicrepublicofiran", "IR"),
    ("israeli", "IL"),
    ("italia", "IT"),
    ("italian", "IT"),
    ("ivorycoast", "CI"),
    ("japanese", "JP"),
    ("jordanian", "JO"),
    ("keelingislands", "CC"),
    ("kenyan", "KE"),
    ("kirghizia", "KG"),
    ("koreademrep", "KP"),
    ("koreanorth", "KP"),
    ("korearep", "KR"),
    ("koreasouth", "KR"),
    ("ksa", "SA"),
    ("kuwaiti", "KW"),
    ("kyrgyzrepublic", "KG"),
    ("laos", "LA"),
    ("lebanese", "LB"),
    ("libyanarabjamahiriya", "LY"),
    ("macaosar", "MO"),
    ("macau", "MO"),
    ("macedonia", "MK"),
    ("magyarorszag", "HU"),
    ("mainlandchina", "CN"),
    ("malaysian", "MY"),
    ("malvinas", "FK"),
    ("mexican", "MX"),
    ("micronesia", "FM"),
    ("moldova", "MD"),
    ("moroccan", "MA"),
    ("nepali", "NP"),
    ("netherlands", "NL"),
    ("nigerian", "NG"),
    ("nihon", "JP"),
    ("nippon", "JP"),
    ("norge", "NO"),
    ("northernireland", "GB"),
    ("northkorea", "KP"),
    ("norwegian", "NO"),
    ("pakistani", "PK"),
    ("palestine", "PS"),
    ("palestinianterritories", "PS"),
    ("peoplesrepublicofchina", "CN"),
    ("peruvian", "PE"),
    ("polish", "PL"),
    ("polska", "PL"),
    ("portuguese", "PT"),
    ("prc", "CN"),
    ("qatari", "QA"),
    ("republicofchina", "TW"),
    ("republicofcongo", "CG"),
    ("republicofireland", "IE"),
    ("republicofkorea", "KR"),
    ("republicofmoldova", "MD"),
    ("republicofsouthafrica", "ZA"),
    ("republicofthecongo", "CG"),
    ("rhodesia", "ZW"),
    ("rok", "KR"),
    ("romanian", "RO"),
    ("rsa", "ZA"),
    ("russia", "RU"),
    ("russian", "RU"),
    ("saintchristopherandnevis", "KN"),
    ("saudi", "SA"),
    ("scotland", "GB"),
    ("scottish", "GB"),
    ("serbian", "RS"),
    ("siam", "TH"),
    ("singaporean", "SG"),
    ("slovakrepublic", "SK"),
    ("southgeorgia", "GS"),
    ("southkorea", "KR"),
    ("spanish", "ES"),
    ("stateofpalestine", "PS"),
    ("stbarthelemy", "BL"),
    ("stbarts", "BL"),
    ("sthelena", "SH"),
    ("stkittsandnevis", "KN"),
    ("stlucia", "LC"),
    ("stmartin", "MF"),
    ("stpierreandmiquelon", "PM"),
    ("stvincent", "VC"),
    ("stvincentandthegrenadines", "VC"),
    ("suomi", "FI"),
    ("svalbard", "SJ"),
    ("sverige", "SE"),
    ("swaziland", "SZ"),
    ("swedish", "SE"),
    ("swiss", "CH"),
    ("syria", "SY"),
    ("taiwan", "TW"),
    ("tanzania", "TZ"),
    ("thai", "TH"),
    ("turkey", "TR"),
    ("turkish", "TR"),
    ("uae", "AE"),
    ("uk", "GB"),
    ("ukrainian", "UA"),
    ("unitedkingdom", "GB"),
    ("unitedrepublicoftanzania", "TZ"),
    ("unitedstates", "US"),
    ("unitedstatesofamerica", "US"),
    ("us", "US"),
    ("usa", "US"),
    ("usminoroutlyingislands", "UM"),
    ("usvi", "VI"),
    ("usvirginislands", "VI"),
    ("vatican", "VA"),
    ("vaticancity", "VA"),
    ("venezuela", "VE"),
    ("vietnam", "VN"),
    ("vietnamese", "VN"),
    ("wales", "GB"),
    ("welsh", "GB"),
    ("westgermany", "DE"),
    ("zaire", "CD"),
];
