#!/usr/bin/env python3
"""Regenerate core/src/tables.rs from the published CDC growth-chart LMS data files.

The CDC growth charts are a work of the U.S. federal government and are in the
public domain, so the L/M/S coefficients can be bundled directly. Run from this
directory:

    python3 build-tables.py

It downloads the eight CDC z-score data files, keeps the (x, L, M, S) columns and
writes them out as sorted Rust constants. Nothing else in the block is generated.
"""

import csv
import io
import urllib.request

BASE = "https://www.cdc.gov/growthcharts/data/zscore/"

# (rust const name, csv file, x column, human label)
SETS = [
    ("LENGTH_FOR_AGE_INFANT", "lenageinf.csv", "Agemos", "CDC length-for-age, 0-36 months"),
    ("WEIGHT_FOR_AGE_INFANT", "wtageinf.csv", "Agemos", "CDC weight-for-age, 0-36 months"),
    ("HEAD_FOR_AGE_INFANT", "hcageinf.csv", "Agemos", "CDC head circumference-for-age, 0-36 months"),
    ("WEIGHT_FOR_LENGTH", "wtleninf.csv", "Length", "CDC weight-for-length, 45-103.5 cm"),
    ("STATURE_FOR_AGE_CHILD", "statage.csv", "Agemos", "CDC stature-for-age, 2-20 years"),
    ("WEIGHT_FOR_AGE_CHILD", "wtage.csv", "Agemos", "CDC weight-for-age, 2-20 years"),
    ("BMI_FOR_AGE_CHILD", "bmiagerev.csv", "Agemos", "CDC BMI-for-age, 2-20 years"),
    ("WEIGHT_FOR_STATURE", "wtstat.csv", "Height", "CDC weight-for-stature, 77-121.5 cm"),
]


def fetch(name):
    with urllib.request.urlopen(BASE + name, timeout=60) as resp:
        text = resp.read().decode("utf-8-sig")
    return list(csv.DictReader(io.StringIO(text)))


def emit(out, const, rows, xcol, label):
    for sex, code in (("BOY", "1"), ("GIRL", "2")):
        picked = sorted(
            (float(r[xcol]), float(r["L"]), float(r["M"]), float(r["S"]))
            for r in rows
            if r["Sex"].strip() == code
        )
        out.write(f"/// {label} ({sex.lower()}s). Source: {BASE}\n")
        out.write(f"pub const {const}_{sex}: [Lms; {len(picked)}] = [\n")
        for x, l, m, s in picked:
            out.write(f"    Lms({x!r}, {l!r}, {m!r}, {s!r}),\n")
        out.write("];\n\n")


def main():
    with open("src/tables.rs", "w") as out:
        out.write(
            "//! CDC growth-chart LMS coefficients — GENERATED by build-tables.py, do not hand-edit.\n"
            "//!\n"
            "//! Source: CDC growth charts z-score data files (https://www.cdc.gov/growthcharts/).\n"
            "//! Work of the U.S. federal government, public domain.\n"
            "//! Each row is (x, L, M, S) where x is age in months or length/stature in cm.\n\n"
            "use crate::Lms;\n\n"
        )
        for const, name, xcol, label in SETS:
            emit(out, const, fetch(name), xcol, label)
    print("wrote src/tables.rs")


if __name__ == "__main__":
    main()
