use std::{env, fs, path::PathBuf};

/// Extract a top-level `key = "value"` string from TOML text without pulling in
/// a toml parser. Returns the first match.
fn toml_str_value(text: &str, key: &str) -> Option<String> {
    for line in text.lines() {
        let line = line.trim();
        if let Some(rest) = line.strip_prefix(key) {
            let rest = rest.trim_start();
            if let Some(rest) = rest.strip_prefix('=') {
                let rest = rest.trim();
                if rest.starts_with('"') && rest.len() >= 2 {
                    if let Some(end) = rest[1..].find('"') {
                        return Some(rest[1..=end].to_string());
                    }
                }
            }
        }
    }
    None
}

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");

    let blocks_dir = PathBuf::from(&manifest_dir).join("blocks");
    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    // (slug, title) for every block exposing a standalone tool page.
    let mut tools: Vec<(String, String)> = Vec::new();

    if blocks_dir.is_dir() {
        for entry in fs::read_dir(&blocks_dir).expect("read blocks/") {
            let entry = entry.expect("blocks/ entry");
            let wasm = entry.path().join("target/block.wasm");
            let manifest = entry.path().join("manifest.json");

            // Standalone tool page metadata — independent of whether the block's
            // WASM is built yet, so scan it before the skip check below.
            let meta_path = entry.path().join("page/meta.toml");
            if meta_path.is_file() {
                println!("cargo:rerun-if-changed={}", meta_path.display());
                let meta_text = fs::read_to_string(&meta_path).expect("read page/meta.toml");
                if let (Some(slug), Some(h1)) = (
                    toml_str_value(&meta_text, "slug"),
                    toml_str_value(&meta_text, "h1"),
                ) {
                    tools.push((slug, h1));
                }
            }

            if !wasm.is_file() || !manifest.is_file() {
                // Skip entries that aren't built yet.
                println!(
                    "cargo:warning=skipping blocks/{} — missing target/block.wasm or manifest.json",
                    entry.file_name().to_string_lossy()
                );
                continue;
            }
            let manifest_text = fs::read_to_string(&manifest).expect("read manifest");
            let manifest_json: serde_json::Value =
                serde_json::from_str(&manifest_text).expect("manifest json");
            let name = manifest_json["name"]
                .as_str()
                .expect("manifest.name")
                .to_string();
            entries.push((name, wasm));
            println!(
                "cargo:rerun-if-changed={}",
                entry.path().join("target/block.wasm").display()
            );
            println!(
                "cargo:rerun-if-changed={}",
                entry.path().join("manifest.json").display()
            );
        }
    }
    println!("cargo:rerun-if-changed=blocks");

    // Sort alphabetically by name for deterministic output.
    entries.sort_by(|a, b| a.0.cmp(&b.0));
    // Sort tools by slug for deterministic output.
    tools.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = String::new();
    out.push_str("// Generated by build.rs — do not edit.\n");
    out.push_str(
        "// Lists every WASM skill block under blocks/ that was built at compile time.\n\n",
    );
    out.push_str("pub const SKILLS: &[(&str, &[u8])] = &[\n");
    for (name, wasm_path) in &entries {
        let escaped = wasm_path.to_string_lossy().replace('\\', "/");
        out.push_str(&format!(
            "    (\"{name}\", include_bytes!(\"{escaped}\")),\n"
        ));
    }
    out.push_str("];\n");

    let dest = PathBuf::from(&out_dir).join("skills.rs");
    fs::write(&dest, out).expect("write skills.rs");

    let mut tools_out = String::new();
    tools_out.push_str("// Generated by build.rs — do not edit.\n");
    tools_out.push_str("// (slug, title) for every tool with a page/meta.toml.\n\n");
    tools_out.push_str("pub const TOOLS: &[(&str, &str)] = &[\n");
    for (slug, title) in &tools {
        let title = title.replace('\\', "\\\\").replace('"', "\\\"");
        tools_out.push_str(&format!("    ({slug:?}, \"{title}\"),\n"));
    }
    tools_out.push_str("];\n");

    let tools_dest = PathBuf::from(&out_dir).join("tools.rs");
    fs::write(&tools_dest, tools_out).expect("write tools.rs");
}
