use std::{env, fs, path::PathBuf};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");

    let blocks_dir = PathBuf::from(&manifest_dir).join("blocks");
    let mut entries: Vec<(String, PathBuf)> = Vec::new();

    if blocks_dir.is_dir() {
        for entry in fs::read_dir(&blocks_dir).expect("read blocks/") {
            let entry = entry.expect("blocks/ entry");
            let wasm = entry.path().join("target/block.wasm");
            let manifest = entry.path().join("manifest.json");

            if !wasm.is_file() || !manifest.is_file() {
                // Skip entries that aren't built yet.
                println!(
                    "cargo:warning=skipping blocks/{} — missing target/block.wasm or manifest.json",
                    entry.file_name().to_string_lossy()
                );
                continue;
            }
            let manifest_text = fs::read_to_string(&manifest).expect("read manifest");
            let manifest_json: serde_json::Value =
                serde_json::from_str(&manifest_text).expect("manifest json");
            let name = manifest_json["name"]
                .as_str()
                .expect("manifest.name")
                .to_string();
            entries.push((name, wasm));
            println!(
                "cargo:rerun-if-changed={}",
                entry.path().join("target/block.wasm").display()
            );
            println!(
                "cargo:rerun-if-changed={}",
                entry.path().join("manifest.json").display()
            );
        }
    }
    println!("cargo:rerun-if-changed=blocks");

    // Sort alphabetically by name for deterministic output.
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = String::new();
    out.push_str("// Generated by build.rs — do not edit.\n");
    out.push_str(
        "// Lists every WASM skill block under blocks/ that was built at compile time.\n\n",
    );
    out.push_str("pub const SKILLS: &[(&str, &[u8])] = &[\n");
    for (name, wasm_path) in &entries {
        let escaped = wasm_path.to_string_lossy().replace('\\', "/");
        out.push_str(&format!(
            "    (\"{name}\", include_bytes!(\"{escaped}\")),\n"
        ));
    }
    out.push_str("];\n");

    let dest = PathBuf::from(&out_dir).join("skills.rs");
    fs::write(&dest, out).expect("write skills.rs");
}
