use std::{env, fs, path::PathBuf};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");

    let blocks_dir = PathBuf::from(&manifest_dir).join("blocks");
    // Do NOT `include_bytes!` block wasm anymore: baking every block into the
    // app cdylib grew `gizza_ai_bg.wasm` ~0.5 MiB per tool and blew past
    // Cloudflare Pages' hard 25 MiB/file limit once ~47 blocks accumulated
    // (26 MiB of embedded wasm). Embed only each block's (small) manifest.json;
    // the wasm is fetched lazily from `/blocks/<slug>.wasm` on first invocation
    // (see src/lazy_skill.rs) and published as a separate static asset at deploy.
    let mut entries: Vec<(String, PathBuf)> = Vec::new();

    if blocks_dir.is_dir() {
        for entry in fs::read_dir(&blocks_dir).expect("read blocks/") {
            let entry = entry.expect("blocks/ entry");
            let slug = entry.file_name().to_string_lossy().to_string();
            let wasm = entry.path().join("target/block.wasm");
            let manifest = entry.path().join("manifest.json");

            if !wasm.is_file() || !manifest.is_file() {
                // Skip entries that aren't built yet. The wasm must still exist
                // at build time (so we know it will be published as an asset);
                // we just no longer embed its bytes.
                println!(
                    "cargo:warning=skipping blocks/{slug} — missing target/block.wasm or manifest.json"
                );
                continue;
            }
            entries.push((slug, manifest));
        }
    }
    println!("cargo:rerun-if-changed=blocks");

    // Sort by slug for deterministic output.
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = String::new();
    out.push_str("// Generated by build.rs — do not edit.\n");
    out.push_str(
        "// (slug, manifest.json) for every WASM skill block under blocks/ built at\n\
         // compile time. The block wasm itself is NOT embedded — it is fetched\n\
         // lazily from /blocks/<slug>.wasm on first use (see src/lazy_skill.rs).\n\n",
    );
    out.push_str("pub const SKILLS: &[(&str, &str)] = &[\n");
    for (slug, manifest_path) in &entries {
        let escaped = manifest_path.to_string_lossy().replace('\\', "/");
        // Re-run if a manifest changes — its embedded JSON drives BlockInfo.
        println!("cargo:rerun-if-changed={escaped}");
        out.push_str(&format!("    (\"{slug}\", include_str!(\"{escaped}\")),\n"));
    }
    out.push_str("];\n");

    let dest = PathBuf::from(&out_dir).join("skills.rs");
    fs::write(&dest, out).expect("write skills.rs");
}
