[package]
name = "gizza-ai-video-audio-track-selector-web"
version = "0.1.0"
edition = "2021"
rust-version = "1.82"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
serde-wasm-bindgen = "0.6"
gizza-ai-block-utils = { path = "../../../block-utils" }
gizza-ai-video-audio-track-selector-core = { path = "../core" }
