import { test, expect } from './fixtures';

const SIMPLE_MAPPING = 'IMG_001.JPG,photo-001.jpg\nIMG_002.JPG,photo-002.jpg';

const SIMPLE_BASH = `#!/usr/bin/env bash
# Rename script generated by mv-script-generator — 2 renames.
# Review this script before running it. Nothing moves until you run it.
set -euo pipefail

mv_safe() {
  local src=$1 dst=$2
  if [ ! -e "$src" ] && [ ! -L "$src" ]; then
    printf 'mv-script: missing source: %s\\n' "$src" >&2
    exit 1
  fi
  if [ -e "$dst" ] || [ -L "$dst" ]; then
    printf 'mv-script: destination exists: %s\\n' "$dst" >&2
    exit 1
  fi
  mkdir -p -- "$(dirname -- "$dst")"
  mv -- "$src" "$dst"
}

mv_safe 'IMG_001.JPG' 'photo-001.jpg'
mv_safe 'IMG_002.JPG' 'photo-002.jpg'
`;

async function runWasm(
  page,
  mapping: string,
  format = 'auto',
  shell = 'bash',
  baseDir = '',
  dryRun = 'false',
  overwrite = 'false',
  mkdirParents = 'true',
  undoScript = 'false',
  comments = 'true',
) {
  return await page.evaluate(async (args) => {
    const mod = await import('/tools/mv-script-generator/gizza_ai_mv_script_generator_web.js');
    await mod.default('/tools/mv-script-generator/gizza_ai_mv_script_generator_web_bg.wasm');
    return mod.run(
      args.mapping,
      args.format,
      args.shell,
      args.baseDir,
      args.dryRun,
      args.overwrite,
      args.mkdirParents,
      args.undoScript,
      args.comments,
    );
  }, { mapping, format, shell, baseDir, dryRun, overwrite, mkdirParents, undoScript, comments });
}

test('mv-script-generator wasm renders a bash rename script exactly', async ({ page }) => {
  await page.goto('/tools/mv-script-generator/');
  await page.waitForSelector('#in-mapping');

  await expect(runWasm(page, SIMPLE_MAPPING)).resolves.toBe(SIMPLE_BASH);
});

test('mv-script-generator wasm covers formats, shells, non-default checkboxes, and pair cap', async ({ page }) => {
  await page.goto('/tools/mv-script-generator/');
  await page.waitForSelector('#in-mapping');

  await expect(runWasm(page, 'a.txt,b.txt', 'csv')).resolves.toContain("mv_safe 'a.txt' 'b.txt'");
  await expect(runWasm(page, 'a.txt\tb.txt', 'tsv')).resolves.toContain("mv_safe 'a.txt' 'b.txt'");
  await expect(runWasm(page, 'a.txt -> b.txt', 'arrow')).resolves.toContain("mv_safe 'a.txt' 'b.txt'");
  await expect(runWasm(page, 'a.txt | b.txt', 'pipe')).resolves.toContain("mv_safe 'a.txt' 'b.txt'");
  await expect(runWasm(page, 'a.txt,b.txt', 'auto')).resolves.toContain("mv_safe 'a.txt' 'b.txt'");

  const ps = await runWasm(page, "it's here.txt,there.txt", 'csv', 'powershell', 'C:\\photos', 'true', 'true', 'false', 'false', 'false');
  expect(ps).toContain('#Requires -Version 5.1');
  expect(ps).toContain("Set-Location -LiteralPath 'C:\\photos'");
  expect(ps).toContain('-WhatIf');
  expect(ps).toContain('-Force');
  expect(ps).toContain("Move-Safe 'it''s here.txt' 'there.txt'");
  expect(ps).not.toContain('New-Item -ItemType Directory');
  expect(ps).not.toContain('# Rename script');
  expect(ps).not.toContain('undo-rename');

  const atCap = Array.from({ length: 1000 }, (_, i) => `a${i}.txt,b${i}.txt`).join('\n');
  await expect(runWasm(page, atCap, 'csv')).resolves.toContain('mv_safe \'a999.txt\' \'b999.txt\'');
  const overCap = `${atCap}\na1000.txt,b1000.txt`;
  await expect(runWasm(page, overCap, 'csv')).rejects.toThrow(/too many rename pairs/);
});

test('mv-script-generator page renders exact output from form controls', async ({ page }) => {
  await page.goto('/tools/mv-script-generator/');
  await page.fill('#in-mapping', SIMPLE_MAPPING);
  await page.uncheck('#in-undo_script');

  await expect(page.locator('#tool-output')).toHaveText(SIMPLE_BASH, { timeout: 15_000 });
});

test('mv-script-generator deep-link prefills controls and renders PowerShell dry run', async ({ page }) => {
  const params = new URLSearchParams({
    mapping: 'a.txt | sub/b.txt',
    format: 'pipe',
    shell: 'powershell',
    base_dir: 'C:\\photos',
    dry_run: 'true',
    overwrite: 'true',
    mkdir_parents: 'false',
    undo_script: 'false',
    comments: 'false',
  });

  await page.goto(`/tools/mv-script-generator/?${params.toString()}`);
  await expect(page.locator('#in-mapping')).toHaveValue('a.txt | sub/b.txt', { timeout: 15_000 });
  await expect(page.locator('#in-format')).toHaveValue('pipe');
  await expect(page.locator('#in-shell')).toHaveValue('powershell');
  await expect(page.locator('#in-base_dir')).toHaveValue('C:\\photos');
  await expect(page.locator('#in-dry_run')).toBeChecked();
  await expect(page.locator('#in-overwrite')).toBeChecked();
  await expect(page.locator('#in-mkdir_parents')).not.toBeChecked();
  await expect(page.locator('#in-undo_script')).not.toBeChecked();
  await expect(page.locator('#in-comments')).not.toBeChecked();

  const output = page.locator('#tool-output');
  await expect(output).toContainText('#Requires -Version 5.1', { timeout: 15_000 });
  await expect(output).toContainText("Set-Location -LiteralPath 'C:\\photos'");
  await expect(output).toContainText('-WhatIf');
  await expect(output).toContainText('-Force');
  await expect(output).toContainText("Move-Safe 'a.txt' 'sub/b.txt'");
});
