import { test, expect } from './fixtures';

const TRIANGLE = `ply
format ascii 1.0
element vertex 3
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
element face 1
property list uchar int vertex_indices
end_header
0 0 0 255 0 0
1 0 0 0 255 0
0 1 0 0 0 255
3 0 1 2`;

const QUAD = `ply
format ascii 1.0
element vertex 4
property float x
property float y
property float z
element face 1
property list uchar int vertex_indices
end_header
0 0 0
1 0 0
1 1 0
0 1 0
4 0 1 2 3`;

async function setField(page: import('@playwright/test').Page, id: string, value: string) {
  await page.locator(id).evaluate((el, v) => {
    (el as HTMLTextAreaElement | HTMLInputElement).value = v;
    el.dispatchEvent(new Event('input', { bubbles: true }));
  }, value);
}

async function outputText(page: import('@playwright/test').Page) {
  return ((await page.locator('#tool-output').textContent()) ?? '').trim();
}

test('ply-to-obj page converts a colored ASCII triangle to exact OBJ', async ({ page }) => {
  await page.goto('/tools/ply-to-obj/');
  await page.waitForSelector('#in-ply');
  await expect(page.locator('#in-input_format')).toHaveValue('auto');
  await expect(page.locator('#in-output')).toHaveValue('obj');

  await setField(page, '#in-ply', TRIANGLE);
  await setField(page, '#in-name', 'colored_tri');

  await expect(page.locator('#tool-output')).toContainText('o colored_tri', { timeout: 20_000 });
  expect(await outputText(page)).toBe(
    '# OBJ generated by gizza ply-to-obj\n' +
      '# source: PLY (ascii), 3 vertices, 1 faces\n' +
      '# vertex colors are the r g b values after each v (0..1)\n' +
      'o colored_tri\n' +
      'v 0 0 0 1 0 0\n' +
      'v 1 0 0 0 1 0\n' +
      'v 0 1 0 0 0 1\n' +
      'f 1 2 3',
  );
});

test('ply-to-obj deep link uses hex input and summary output', async ({ page }) => {
  const hex = Buffer.from(TRIANGLE, 'utf8').toString('hex');
  const params = new URLSearchParams({
    ply: hex,
    input_format: 'hex',
    colors: 'true',
    normals: 'true',
    uvs: 'true',
    triangulate: 'false',
    scale: '1',
    axis: 'keep',
    name: 'hex_tri',
    output: 'summary',
  });
  await page.goto(`/tools/ply-to-obj/?${params.toString()}`);

  await expect(page.locator('#in-input_format')).toHaveValue('hex', { timeout: 15_000 });
  await expect(page.locator('#in-output')).toHaveValue('summary');
  const out = page.locator('#tool-output');
  await expect(out).toContainText('PLY → OBJ conversion summary', { timeout: 20_000 });
  await expect(out).toContainText('source encoding:   PLY ascii');
  await expect(out).toContainText('vertices:          3');
  await expect(out).toContainText('vertex colors:     yes in source, yes written');
});

test('ply-to-obj supports enum choices, non-default checkbox state, and transforms', async ({ page }) => {
  await page.goto('/tools/ply-to-obj/');
  await setField(page, '#in-ply', QUAD);
  await page.selectOption('#in-input_format', 'ascii');
  await page.uncheck('#in-colors');
  await page.uncheck('#in-normals');
  await page.uncheck('#in-uvs');
  await page.check('#in-triangulate');
  await setField(page, '#in-scale', '25.4');
  await page.selectOption('#in-axis', 'y-up-to-z-up');
  await setField(page, '#in-name', 'plate');

  const out = page.locator('#tool-output');
  await expect(out).toContainText('o plate', { timeout: 20_000 });
  await expect(out).toContainText('v 25.4 0 0');
  await expect(out).toContainText('v 25.4 0 25.4');
  expect(await outputText(page)).toContain('f 1 2 3\nf 1 3 4');
});

test('ply-to-obj page ships runnable CLI, labels, and preset chips', async ({ page }) => {
  await page.goto('/tools/ply-to-obj/');
  const cli = (await page.locator('.tool-cli-code').first().textContent())!.trim();
  expect(cli).toContain('gizza tool ply-to-obj');
  expect(cli).toContain('format ascii 1.0');
  expect(cli).not.toContain('TODO');
  expect(cli).not.toContain('gizza.ai');
  await expect(page.locator('#in-input_format option[value="base64"]')).toHaveText('Binary PLY as base64');
  await expect(page.locator('#in-axis option[value="y-up-to-z-up"]')).toHaveText('Y-up → Z-up');
  await expect(page.locator('#in-output option[value="summary"]')).toHaveText('Source-file summary');
  await expect(page.locator('.tool-example-chip')).toHaveCount(4);
});
