//! gizza-ai/social-image-resize — fetch an image URL or attachment ref, resize +
//! crop it to a social-media preset via ffmpeg, and return a media envelope.
#![cfg_attr(not(target_arch = "wasm32"), allow(dead_code, unused_imports))]

use gizza_ai_block_utils::{
    build_media_envelope, filename_with_suffix, mime_to_ext, AssetKind, Input, Param, SkillError,
    SkillResultExt, SourceFields, ToolDescriptor,
};
#[cfg(target_arch = "wasm32")]
use gizza_ai_block_utils::{dispatch_ffmpeg, resolve_source};
use gizza_ai_social_image_resize_core::{plan, target_dims};
use serde::Deserialize;
use wafer_sdk::*;

const MAX_INPUT_BYTES: usize = 20 * 1024 * 1024;
const MAX_OUTPUT_BYTES: usize = 20 * 1024 * 1024;

#[derive(Deserialize, Debug)]
struct Args {
    #[serde(flatten)]
    source: SourceFields,
    #[serde(default)]
    target: Option<String>,
    #[serde(default)]
    fit: Option<String>,
    #[serde(default)]
    gravity: Option<String>,
    #[serde(default)]
    background: Option<String>,
}

fn descriptor() -> ToolDescriptor {
    ToolDescriptor::new(Input::Image)
        .param(
            Param::enumv(
                "target",
                [
                    "instagram-square",
                    "instagram-portrait",
                    "instagram-story",
                    "facebook-post",
                    "facebook-cover",
                    "twitter-post",
                    "twitter-header",
                    "linkedin-post",
                    "linkedin-cover",
                    "youtube-thumbnail",
                    "pinterest-pin",
                    "tiktok-video",
                ],
            )
            .default("instagram-square")
            .describe("Social-media size preset. instagram-square=1080x1080, instagram-portrait=1080x1350, instagram-story=1080x1920, facebook-post=1200x630, facebook-cover=820x312, twitter-post=1600x900, twitter-header=1500x500, linkedin-post=1200x627, linkedin-cover=1584x396, youtube-thumbnail=1280x720, pinterest-pin=1000x1500, tiktok-video=1080x1920. Default instagram-square."),
        )
        .param(
            Param::enumv("fit", ["cover", "contain", "stretch"])
                .default("cover")
                .describe("How the source fills the target box: cover (default) scales up and crops overflow; contain scales down inside the box and pads with background; stretch forces the exact size and may distort."),
        )
        .param(
            Param::enumv("gravity", ["center", "top", "bottom"])
                .default("center")
                .describe("Which part to keep when fit=cover crops overflow: center (default), top, or bottom. Ignored for contain/stretch."),
        )
        .param(
            Param::string("background")
                .default("white")
                .describe("Padding colour used when fit=contain, as #rgb, #rgba, #rrggbb, #rrggbbaa, or a plain colour name. Default white. Ignored for cover/stretch."),
        )
}

fn schema_json() -> String {
    descriptor().to_schema_json()
}

#[cfg(target_arch = "wasm32")]
struct Tool;

#[cfg(target_arch = "wasm32")]
#[wafer_block(
    name = "gizza-ai/social-image-resize",
    version = "0.1.0",
    interface = "handler@v1",
    summary = "Resize and crop an image to social media preset sizes.",
    requires = ["wafer-run/network", "gizza-ai/ffmpeg-runtime"],
    capabilities(network, callable_blocks = ["wafer-run/network", "gizza-ai/ffmpeg-runtime"]),
    skill(
        description = "Resize and crop an image to a chosen social-media preset size: Instagram square/portrait/story, Facebook post/cover, X/Twitter post/header, LinkedIn post/cover, YouTube thumbnail, Pinterest pin, or TikTok vertical video. fit=cover (default) fills and crops, contain pads with background, and stretch forces exact dimensions. gravity controls top/center/bottom crop for cover. Output keeps the input image format and is generated by ffmpeg.",
        parameters = schema_json()
    ),
)]
impl Tool {
    fn handle(_msg: Message, body: Vec<u8>) -> GuestResult {
        match run(body) {
            Ok(v) => GuestResult::respond(v),
            Err(e) => GuestResult::error(e.into()),
        }
    }
}

#[cfg(target_arch = "wasm32")]
fn run(body: Vec<u8>) -> Result<Vec<u8>, SkillError> {
    let args: Args = serde_json::from_slice(&body).invalid_args("social-image-resize")?;
    let target = args.target.as_deref().unwrap_or("instagram-square");
    let t = target_dims(target).map_err(SkillError::InvalidArgs)?;
    let (input_bytes, mime, in_filename) =
        resolve_source(args.source.into_inner(), AssetKind::Image, MAX_INPUT_BYTES)?;
    let ext = mime_to_ext(&mime)
        .ok_or_else(|| SkillError::InvalidArgs(format!("unsupported input mime: {mime}")))?;
    let ffmpeg_in = format!("in.{ext}");
    let background = args.background.as_deref().unwrap_or("white");
    let (mut argv, _out_name) = plan(
        &ffmpeg_in,
        target,
        args.fit.as_deref(),
        args.gravity.as_deref(),
        background,
    )
    .map_err(SkillError::InvalidArgs)?;
    let ffmpeg_out = format!("out.{ext}");
    if let Some(last) = argv.last_mut() {
        *last = ffmpeg_out.clone();
    }
    let output = dispatch_ffmpeg(argv, ffmpeg_in, input_bytes, ffmpeg_out)?;
    let output_size = output.len();
    let filename = filename_with_suffix(&in_filename, &format!("-{}-{}x{}", t.name, t.w, t.h), ext);
    let for_llm = format!(
        "resized {in_filename} to {} ({}x{}, {output_size} bytes {mime})",
        t.name, t.w, t.h
    );
    build_media_envelope(&output, &mime, filename, for_llm, MAX_OUTPUT_BYTES)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn schema_has_expected_social_params() {
        let schema: serde_json::Value = serde_json::from_str(&schema_json()).unwrap();
        let props = schema.get("properties").unwrap();
        assert!(props.get("url").is_some());
        assert!(props.get("ref").is_some());
        assert_eq!(props["target"]["default"], "instagram-square");
        assert_eq!(props["fit"]["enum"].as_array().unwrap().len(), 3);
        assert_eq!(props["gravity"]["default"], "center");
        assert_eq!(props["background"]["default"], "white");
    }
}
