//! gizza-ai/video-add-silent-audio — fetch a video URL or attachment ref, give
//! it a silent audio track via ffmpeg, and return an envelope. The picture is
//! stream-copied (`-c:v copy`, lossless); the silence is synthesised by the
//! `anullsrc` filter source, so this stays a SINGLE-input tool (no second media
//! file to supply). The chat schema is derived from `descriptor()` (single
//! source — shared across chat + CLI + page); source-resolution, ffmpeg
//! dispatch, and envelope-building are delegated to `block_utils`. Option
//! parsing and the pure argv builder live in `core`.
//!
//! NOTE: chat ffmpeg is non-functional (the chat runtime is a Service Worker
//! where ffmpeg can't load), so the supported surfaces are the standalone page
//! and the CLI.
#![cfg_attr(not(target_arch = "wasm32"), allow(dead_code, unused_imports))]

use gizza_ai_block_utils::{
    build_media_envelope, filename_with_suffix, mime_to_ext, AssetKind, Input, Param, SkillError,
    SkillResultExt, SourceFields, ToolDescriptor,
};
#[cfg(target_arch = "wasm32")]
use gizza_ai_block_utils::{dispatch_ffmpeg, resolve_source};
use gizza_ai_video_add_silent_audio_core::{effective_sample_rate, plan};
use serde::Deserialize;
use wafer_sdk::*;

const MAX_INPUT_BYTES: usize = 25 * 1024 * 1024; // 25 MiB
const MAX_OUTPUT_BYTES: usize = 25 * 1024 * 1024;

#[derive(Deserialize, Debug)]
struct Args {
    #[serde(flatten)]
    source: SourceFields,
    #[serde(default)]
    channels: Option<String>,
    #[serde(default)]
    sample_rate: Option<String>,
    #[serde(default)]
    bitrate: Option<String>,
    #[serde(default)]
    existing_audio: Option<String>,
}

/// Single-source param descriptor → chat schema (and CLI + page). The
/// drift-guard test below proves the derived schema matches the authored one.
fn descriptor() -> ToolDescriptor {
    ToolDescriptor::new(Input::Video)
        .param(
            Param::enumv("channels", ["mono", "stereo"])
                .default("stereo")
                .describe("Channel layout of the silent track: 'stereo' (default — what most upload validators expect) or 'mono' (half the size, still a valid audio stream). The track is digital silence either way."),
        )
        .param(
            Param::enumv("sample_rate", ["22050", "44100", "48000"])
                .default("48000")
                .describe("Sample rate of the silent track in Hz: 48000 (default, the video-world standard), 44100 (CD/editor-friendly) or 22050 (smallest). WebM output is always 48000 because Opus only encodes at that rate."),
        )
        .param(
            Param::enumv("bitrate", ["32", "64", "96", "128", "192"])
                .default("128")
                .describe("Audio bitrate of the silent track in kbps: 128 (default, universally accepted), 32/64 to keep the added bytes negligible on a long clip, 192 if a strict validator wants a higher rate. Silence sounds identical at every value."),
        )
        .param(
            Param::enumv("existing_audio", ["replace", "keep"])
                .default("replace")
                .describe("What to do if the video ALREADY has an audio track: 'replace' (default — the output carries exactly one track, the silence, so the clip ends up muted) or 'keep' (the existing track is kept and the silence is added as a second track; the existing track is re-encoded at the chosen bitrate). For a video with no audio both behave identically."),
        )
}

fn schema_json() -> String {
    descriptor().to_schema_json()
}

#[cfg(target_arch = "wasm32")]
fn ext_to_video_mime(ext: &str) -> &'static str {
    match ext {
        "webm" => "video/webm",
        "mov" => "video/quicktime",
        "mkv" => "video/x-matroska",
        _ => "video/mp4",
    }
}

#[cfg(target_arch = "wasm32")]
struct VideoAddSilentAudio;

#[cfg(target_arch = "wasm32")]
#[wafer_block(
    name = "gizza-ai/video-add-silent-audio",
    version = "0.1.0",
    interface = "handler@v1",
    summary = "Add a silent audio track to a video that has none so upload checks accept it",
    requires = ["wafer-run/network", "gizza-ai/ffmpeg-runtime"],
    capabilities(network, callable_blocks = ["wafer-run/network", "gizza-ai/ffmpeg-runtime"]),
    skill(
        description = "Add a track of pure digital silence to a video that has NO audio stream, so platforms, editors and players that require an audio stream accept it. The picture is stream-copied (`-c:v copy`) — lossless, fast, byte-identical — and the silence is generated by ffmpeg's anullsrc filter, so no second file is needed. Provide either url (HTTP/HTTPS) or ref (id from a prior tool call). Options: channels (mono|stereo, default stereo), sample_rate (22050|44100|48000 Hz, default 48000), bitrate (32|64|96|128|192 kbps, default 128), existing_audio (replace|keep, default replace — 'replace' leaves exactly one silent track, 'keep' preserves an existing track and adds silence as a second one). The silence is bounded to the video's length and the output keeps the input container (WebM gets Opus at 48 kHz, everything else AAC). Note: runs on the standalone page and the CLI (chat ffmpeg is unavailable).",
        parameters = schema_json()
    ),
)]
impl VideoAddSilentAudio {
    fn handle(_msg: Message, body: Vec<u8>) -> GuestResult {
        match run(body) {
            Ok(v) => GuestResult::respond(v),
            Err(e) => GuestResult::error(e.into()),
        }
    }
}

#[cfg(target_arch = "wasm32")]
fn run(body: Vec<u8>) -> Result<Vec<u8>, SkillError> {
    // 1. Parse args; option validation lives in core's plan.
    let args: Args = serde_json::from_slice(&body).invalid_args("video-add-silent-audio")?;
    let channels = args.channels.as_deref().unwrap_or("stereo");
    let sample_rate = args.sample_rate.as_deref().unwrap_or("48000");
    let bitrate = args.bitrate.as_deref().unwrap_or("128");
    let existing_audio = args.existing_audio.as_deref().unwrap_or("replace");

    // 2. Resolve source — URL fetch or attachment lookup (video/* MIME class).
    let (input_bytes, in_mime, in_filename) =
        resolve_source(args.source.into_inner(), AssetKind::Video, MAX_INPUT_BYTES)?;

    // 3. Build ffmpeg argv (shared pure core — validates every option).
    let in_ext = mime_to_ext(&in_mime).unwrap_or("mp4");
    let ffmpeg_in = format!("in.{in_ext}");
    let (argv, ffmpeg_out) = plan(&ffmpeg_in, channels, sample_rate, bitrate, existing_audio)
        .map_err(SkillError::InvalidArgs)?;
    let out_rate =
        effective_sample_rate(&ffmpeg_in, sample_rate).map_err(SkillError::InvalidArgs)?;

    // 4. Dispatch to ffmpeg-runtime.
    let output = dispatch_ffmpeg(argv, ffmpeg_in, input_bytes, ffmpeg_out.clone())?;

    // 5. Envelope with the output container's mime.
    let out_ext = ffmpeg_out.rsplit_once('.').map(|(_, e)| e).unwrap_or("mp4");
    let out_mime = ext_to_video_mime(out_ext);
    let output_size = output.len();
    let filename = filename_with_suffix(&in_filename, "-silent-audio", out_ext);
    let for_llm = format!(
        "added a silent {channels} audio track ({out_rate} Hz, {bitrate} kbps) to {in_filename} ({output_size} bytes {out_mime})"
    );
    build_media_envelope(&output, out_mime, filename, for_llm, MAX_OUTPUT_BYTES)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Drift guard: the descriptor-derived chat schema must match this authored
    /// schema (Input::Video url⊕ref oneOf + the four option enums), so any
    /// future change to the LLM-facing API is intentional and reviewed.
    #[test]
    fn schema_json_matches_authored_chat_schema() {
        let authored: serde_json::Value = serde_json::from_str(
            r#"{
                "type": "object",
                "properties": {
                    "url":            { "type": "string", "description": "Video URL (HTTP/HTTPS). Use either url or ref." },
                    "ref":            { "type": "string", "description": "Reference id from a prior tool call. Use either url or ref." },
                    "channels":       { "type": "string", "enum": ["mono", "stereo"], "default": "stereo", "description": "Channel layout of the silent track: 'stereo' (default — what most upload validators expect) or 'mono' (half the size, still a valid audio stream). The track is digital silence either way." },
                    "sample_rate":    { "type": "string", "enum": ["22050", "44100", "48000"], "default": "48000", "description": "Sample rate of the silent track in Hz: 48000 (default, the video-world standard), 44100 (CD/editor-friendly) or 22050 (smallest). WebM output is always 48000 because Opus only encodes at that rate." },
                    "bitrate":        { "type": "string", "enum": ["32", "64", "96", "128", "192"], "default": "128", "description": "Audio bitrate of the silent track in kbps: 128 (default, universally accepted), 32/64 to keep the added bytes negligible on a long clip, 192 if a strict validator wants a higher rate. Silence sounds identical at every value." },
                    "existing_audio": { "type": "string", "enum": ["replace", "keep"], "default": "replace", "description": "What to do if the video ALREADY has an audio track: 'replace' (default — the output carries exactly one track, the silence, so the clip ends up muted) or 'keep' (the existing track is kept and the silence is added as a second track; the existing track is re-encoded at the chosen bitrate). For a video with no audio both behave identically." }
                },
                "additionalProperties": false,
                "oneOf": [{ "required": ["url"] }, { "required": ["ref"] }]
            }"#,
        )
        .unwrap();
        let derived: serde_json::Value = serde_json::from_str(&schema_json()).unwrap();
        assert_eq!(derived, authored, "no LLM-facing chat-schema drift");
    }

    #[test]
    fn output_filename_uses_silent_audio_suffix() {
        assert_eq!(
            filename_with_suffix("clip.mp4", "-silent-audio", "mp4"),
            "clip-silent-audio.mp4"
        );
    }
}
