//! child-growth-percentile core — pure compute, shared by the chat skill block and the web page.
//! No wafer/wasm-bindgen deps.
//!
//! Turns a child's age, sex and measurements into growth-chart percentiles and z-scores using the
//! bundled CDC growth-chart LMS coefficients (see `tables.rs`, generated by `build-tables.py`).
//!
//! The LMS method: for a measurement `X` at an age where the reference has parameters L (Box-Cox
//! power), M (median) and S (coefficient of variation),
//!
//! ```text
//! z = ((X / M)^L - 1) / (L * S)      for L != 0
//! z = ln(X / M) / S                  for L == 0
//! ```
//!
//! and the percentile is the standard-normal CDF of `z`, times 100. L, M and S are interpolated
//! linearly between the two nearest table rows, which is what the CDC's own SAS program does.

pub mod tables;

/// One reference row: (x, L, M, S) where x is age in months or length/stature in cm.
pub struct Lms(pub f64, pub f64, pub f64, pub f64);

/// Oldest age the CDC 2-20 years charts cover, in months (20 years).
pub const MAX_AGE_MONTHS: f64 = 240.0;
/// Oldest age the CDC infant charts cover, in months (3 years).
pub const MAX_INFANT_AGE_MONTHS: f64 = 36.0;
/// Age at which the CDC 2-20 years charts start, in months (2 years).
pub const CHILD_CHART_START_MONTHS: f64 = 24.0;
/// Largest rounding precision accepted for the reported numbers.
pub const MAX_DECIMALS: u32 = 4;
/// Mean days per month used to convert days (and date ranges) to months, matching the CDC.
pub const DAYS_PER_MONTH: f64 = 30.4375;

const CM_PER_INCH: f64 = 2.54;
const KG_PER_POUND: f64 = 0.45359237;
/// Standard-normal quantile at the 95th percentile, used for the severe-obesity cut-off.
const Z_AT_P95: f64 = 1.6448536269514722;

/// Which sex-specific reference curves to read.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Sex {
    Boy,
    Girl,
}

impl Sex {
    pub fn parse(s: &str) -> Result<Self, String> {
        match s.trim().to_ascii_lowercase().as_str() {
            "boy" | "boys" | "male" | "m" | "b" => Ok(Sex::Boy),
            "girl" | "girls" | "female" | "f" | "g" => Ok(Sex::Girl),
            other => Err(format!(
                "Unknown sex '{other}'. Use boy or girl (male/female are accepted too)."
            )),
        }
    }

    fn label(self) -> &'static str {
        match self {
            Sex::Boy => "boy",
            Sex::Girl => "girl",
        }
    }
}

/// Measurement units the caller supplies (and the report echoes back).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Units {
    /// Centimetres and kilograms.
    Metric,
    /// Inches and pounds.
    Us,
}

impl Units {
    pub fn parse(s: &str) -> Result<Self, String> {
        match s.trim().to_ascii_lowercase().as_str() {
            "" | "metric" | "si" | "cm" | "kg" => Ok(Units::Metric),
            "us" | "imperial" | "english" | "in" | "lb" => Ok(Units::Us),
            other => Err(format!(
                "Unknown units '{other}'. Use metric (cm/kg) or us (in/lb)."
            )),
        }
    }

    fn length_unit(self) -> &'static str {
        match self {
            Units::Metric => "cm",
            Units::Us => "in",
        }
    }

    fn mass_unit(self) -> &'static str {
        match self {
            Units::Metric => "kg",
            Units::Us => "lb",
        }
    }

    fn to_cm(self, v: f64) -> f64 {
        match self {
            Units::Metric => v,
            Units::Us => v * CM_PER_INCH,
        }
    }

    fn to_kg(self, v: f64) -> f64 {
        match self {
            Units::Metric => v,
            Units::Us => v * KG_PER_POUND,
        }
    }
}

/// Which CDC reference set to read. The two sets overlap between 24 and 36 months.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Chart {
    /// Infant charts below 24 months, the 2-20 years charts from 24 months.
    Auto,
    /// CDC infant charts (birth to 36 months), recumbent length.
    Infant,
    /// CDC 2-20 years charts, standing stature.
    Child,
}

impl Chart {
    pub fn parse(s: &str) -> Result<Self, String> {
        match s.trim().to_ascii_lowercase().as_str() {
            "" | "auto" => Ok(Chart::Auto),
            "infant" | "0-36" | "birth-36" => Ok(Chart::Infant),
            "child" | "2-20" => Ok(Chart::Child),
            other => Err(format!(
                "Unknown chart '{other}'. Use auto, infant (birth-36 months) or child (2-20 years)."
            )),
        }
    }

    fn resolve(self, age_months: f64) -> Result<Chart, String> {
        match self {
            Chart::Auto => Ok(if age_months < CHILD_CHART_START_MONTHS {
                Chart::Infant
            } else {
                Chart::Child
            }),
            Chart::Infant if age_months > MAX_INFANT_AGE_MONTHS => Err(format!(
                "chart=infant covers birth to {MAX_INFANT_AGE_MONTHS} months; age is {age_months} months. Use chart=child or chart=auto."
            )),
            Chart::Child if age_months < CHILD_CHART_START_MONTHS => Err(format!(
                "chart=child starts at {CHILD_CHART_START_MONTHS} months (2 years); age is {age_months} months. Use chart=infant or chart=auto."
            )),
            other => Ok(other),
        }
    }

    fn label(self) -> &'static str {
        match self {
            Chart::Infant => "CDC infant growth charts (birth to 36 months, recumbent length)",
            _ => "CDC 2-20 years growth charts (standing stature)",
        }
    }
}

/// Everything one run needs. Lengths/weights are in the caller's `units`;
/// a value of `0.0` means "this measurement was not taken".
pub struct Options {
    pub sex: Sex,
    /// Age in months, 0 to 240.
    pub age_months: f64,
    /// Length or height, in cm or inches. 0 = not measured.
    pub height: f64,
    /// Weight, in kg or pounds. 0 = not measured.
    pub weight: f64,
    /// Head circumference, in cm or inches. 0 = not measured.
    pub head_circumference: f64,
    pub units: Units,
    pub chart: Chart,
    pub decimals: u32,
}

/// Validate a caller-supplied rounding precision.
pub fn decimals_from(v: i64) -> Result<u32, String> {
    if !(0..=MAX_DECIMALS as i64).contains(&v) {
        return Err(format!(
            "decimals must be between 0 and {MAX_DECIMALS}, got {v}."
        ));
    }
    Ok(v as u32)
}

/// Parse a flexible age string into months.
///
/// Accepts a bare number (months, the CDC convention), unit-tagged parts in any combination
/// (`3y`, `3y 4m`, `18 months`, `6 weeks`, `95 days`), or a date range written as
/// `YYYY-MM-DD to YYYY-MM-DD` / `YYYY-MM-DD..YYYY-MM-DD`, which is converted with the CDC's
/// 30.4375 days-per-month factor.
pub fn parse_age(input: &str) -> Result<f64, String> {
    let raw = input.trim();
    if raw.is_empty() {
        return Err(
            "Age is required. Give months (36), years and months (3y 4m), or a date range (2023-04-15 to 2026-08-23)."
                .into(),
        );
    }
    if let Some(months) = parse_date_range(raw)? {
        return Ok(months);
    }

    let chars: Vec<char> = raw.to_ascii_lowercase().chars().collect();
    let mut i = 0usize;
    let mut total = 0.0f64;
    let mut parts = 0usize;
    let mut untagged: Option<f64> = None;
    while i < chars.len() {
        if chars[i].is_whitespace() || chars[i] == ',' || chars[i] == '+' {
            i += 1;
            continue;
        }
        let start = i;
        while i < chars.len() && (chars[i].is_ascii_digit() || chars[i] == '.') {
            i += 1;
        }
        if i == start {
            return Err(format!(
                "Could not read the age '{raw}'. Use months (36), years and months (3y 4m), or a date range (2023-04-15 to 2026-08-23)."
            ));
        }
        let number: String = chars[start..i].iter().collect();
        let value: f64 = number.parse().map_err(|_| {
            format!("'{number}' in the age '{raw}' is not a number. Try 36, 3y 4m, or 18 months.")
        })?;
        while i < chars.len() && chars[i].is_whitespace() {
            i += 1;
        }
        let ustart = i;
        while i < chars.len() && chars[i].is_ascii_alphabetic() {
            i += 1;
        }
        let unit: String = chars[ustart..i].iter().collect();
        parts += 1;
        if unit.is_empty() {
            untagged = Some(value);
        } else {
            total += value * months_per_unit(&unit, raw)?;
        }
    }
    match (parts, untagged) {
        (1, Some(v)) => Ok(v),
        (_, Some(_)) => Err(format!(
            "Every part of the age '{raw}' needs a unit when there is more than one. Write it as '3y 4m'."
        )),
        _ => Ok(total),
    }
}

fn months_per_unit(unit: &str, raw: &str) -> Result<f64, String> {
    match unit {
        "y" | "yr" | "yrs" | "year" | "years" => Ok(12.0),
        "m" | "mo" | "mos" | "month" | "months" => Ok(1.0),
        "w" | "wk" | "wks" | "week" | "weeks" => Ok(7.0 / DAYS_PER_MONTH),
        "d" | "day" | "days" => Ok(1.0 / DAYS_PER_MONTH),
        other => Err(format!(
            "Unknown age unit '{other}' in '{raw}'. Use y/years, m/months, w/weeks or d/days."
        )),
    }
}

/// `Some(months)` when the string is a `date to date` range, `None` when it is not a range at all.
fn parse_date_range(raw: &str) -> Result<Option<f64>, String> {
    let lower = raw.to_ascii_lowercase();
    let split = if lower.contains("..") {
        lower
            .splitn(2, "..")
            .map(str::to_string)
            .collect::<Vec<_>>()
    } else if lower.contains(" to ") {
        lower
            .splitn(2, " to ")
            .map(str::to_string)
            .collect::<Vec<_>>()
    } else {
        return Ok(None);
    };
    let birth = parse_iso_date(split[0].trim())?;
    let visit = parse_iso_date(split[1].trim())?;
    let days = (days_from_civil(visit) - days_from_civil(birth)) as f64;
    if days < 0.0 {
        return Err(format!(
            "The measurement date in '{raw}' is before the birth date. Write it as 'birth-date to measurement-date'."
        ));
    }
    Ok(Some(days / DAYS_PER_MONTH))
}

fn parse_iso_date(s: &str) -> Result<(i64, u32, u32), String> {
    let parts: Vec<&str> = s.split('-').collect();
    let bad = || format!("'{s}' is not a date. Use the YYYY-MM-DD form, e.g. 2023-04-15.");
    if parts.len() != 3 {
        return Err(bad());
    }
    let y: i64 = parts[0].parse().map_err(|_| bad())?;
    let m: u32 = parts[1].parse().map_err(|_| bad())?;
    let d: u32 = parts[2].parse().map_err(|_| bad())?;
    if !(1..=12).contains(&m) || !(1..=31).contains(&d) {
        return Err(bad());
    }
    Ok((y, m, d))
}

/// Days since 1970-01-01 (Howard Hinnant's `days_from_civil`).
fn days_from_civil((y, m, d): (i64, u32, u32)) -> i64 {
    let y = if m <= 2 { y - 1 } else { y };
    let era = if y >= 0 { y } else { y - 399 } / 400;
    let yoe = y - era * 400;
    let mp = (m as i64 + 9) % 12;
    let doy = (153 * mp + 2) / 5 + d as i64 - 1;
    let doe = yoe * 365 + yoe / 4 - yoe / 100 + doy;
    era * 146097 + doe - 719468
}

/// Standard-normal CDF (Hart's rational approximation — double precision throughout).
fn norm_cdf(z: f64) -> f64 {
    let x = z.abs();
    let tail = if x > 37.0 {
        0.0
    } else {
        let e = (-x * x / 2.0).exp();
        if x < 7.071_067_811_865_47 {
            let mut num = 3.526_249_659_989_11e-2 * x + 0.700_383_064_443_688;
            num = num * x + 6.373_962_203_531_65;
            num = num * x + 33.912_866_078_383;
            num = num * x + 112.079_291_497_871;
            num = num * x + 221.213_596_169_931;
            num = num * x + 220.206_867_912_376;
            num *= e;
            let mut den = 8.838_834_764_831_84e-2 * x + 1.755_667_163_182_64;
            den = den * x + 16.064_177_579_207;
            den = den * x + 86.780_732_202_946_1;
            den = den * x + 296.564_248_779_674;
            den = den * x + 637.333_633_378_831;
            den = den * x + 793.826_512_519_948;
            den = den * x + 440.413_735_824_752;
            num / den
        } else {
            let mut b = x + 0.65;
            b = x + 4.0 / b;
            b = x + 3.0 / b;
            b = x + 2.0 / b;
            b = x + 1.0 / b;
            e / b / 2.506_628_274_631
        }
    };
    if z > 0.0 {
        1.0 - tail
    } else {
        tail
    }
}

/// Interpolate (L, M, S) at `x`, or `None` when `x` is outside the table.
fn lookup(table: &[Lms], x: f64) -> Option<(f64, f64, f64)> {
    let first = table.first()?;
    let last = table.last()?;
    if x < first.0 || x > last.0 {
        return None;
    }
    let mut lo = 0usize;
    let mut hi = table.len() - 1;
    while hi - lo > 1 {
        let mid = (lo + hi) / 2;
        if table[mid].0 <= x {
            lo = mid;
        } else {
            hi = mid;
        }
    }
    let a = &table[lo];
    let b = &table[hi];
    let span = b.0 - a.0;
    let t = if span <= 0.0 { 0.0 } else { (x - a.0) / span };
    Some((
        a.1 + t * (b.1 - a.1),
        a.2 + t * (b.2 - a.2),
        a.3 + t * (b.3 - a.3),
    ))
}

/// z-score of `value` under the LMS parameters at `x`.
fn z_score(table: &[Lms], x: f64, value: f64) -> Option<f64> {
    let (l, m, s) = lookup(table, x)?;
    if value <= 0.0 || m <= 0.0 || s == 0.0 {
        return None;
    }
    Some(if l.abs() < 1e-9 {
        (value / m).ln() / s
    } else {
        ((value / m).powf(l) - 1.0) / (l * s)
    })
}

/// The measurement sitting at standard-normal score `z` under the LMS parameters at `x`.
fn value_at_z(table: &[Lms], x: f64, z: f64) -> Option<f64> {
    let (l, m, s) = lookup(table, x)?;
    Some(if l.abs() < 1e-9 {
        m * (s * z).exp()
    } else {
        m * (1.0 + l * s * z).powf(1.0 / l)
    })
}

fn table_range(table: &[Lms]) -> (f64, f64) {
    (
        table.first().map(|r| r.0).unwrap_or(0.0),
        table.last().map(|r| r.0).unwrap_or(0.0),
    )
}

/// Round to `decimals` places and trim trailing zeros, so 16.40 prints as 16.4.
fn fmt_num(v: f64, decimals: u32) -> String {
    let s = format!("{v:.*}", decimals as usize);
    if !s.contains('.') {
        return s;
    }
    let trimmed = s.trim_end_matches('0').trim_end_matches('.');
    if trimmed.is_empty() || trimmed == "-" {
        "0".into()
    } else {
        trimmed.to_string()
    }
}

fn fmt_percentile(p: f64, decimals: u32) -> String {
    if p < 0.01 {
        "<0.01".into()
    } else if p > 99.99 {
        ">99.99".into()
    } else {
        fmt_num(p, decimals)
    }
}

fn fmt_age(age_months: f64) -> String {
    let years = (age_months / 12.0).floor() as i64;
    let rest = age_months - years as f64 * 12.0;
    if years == 0 {
        format!("{} months", fmt_num(age_months, 1))
    } else {
        format!("{years} y {} mo", fmt_num(rest, 1))
    }
}

fn pick<'a>(sex: Sex, boy: &'a [Lms], girl: &'a [Lms]) -> &'a [Lms] {
    match sex {
        Sex::Boy => boy,
        Sex::Girl => girl,
    }
}

/// CDC weight-status category for a BMI-for-age percentile (ages 2-20 only).
fn bmi_category(percentile: f64, bmi: f64, p95_bmi: f64) -> String {
    if bmi >= 1.2 * p95_bmi || bmi >= 35.0 {
        return "Severe obesity (BMI at or above 120% of the 95th percentile, or 35 kg/m2)".into();
    }
    if percentile < 5.0 {
        "Underweight (below the 5th percentile)".into()
    } else if percentile < 85.0 {
        "Healthy weight (5th to below the 85th percentile)".into()
    } else if percentile < 95.0 {
        "Overweight (85th to below the 95th percentile)".into()
    } else {
        "Obesity (at or above the 95th percentile)".into()
    }
}

/// Compute the growth report. `Err` carries a message meant to be shown to the user verbatim.
pub fn report(opts: &Options) -> Result<String, String> {
    let Options {
        sex,
        age_months,
        units,
        decimals,
        ..
    } = *opts;

    if !age_months.is_finite() || age_months < 0.0 {
        return Err("Age must be zero or more months.".into());
    }
    if age_months > MAX_AGE_MONTHS {
        return Err(format!(
            "The CDC growth charts stop at {MAX_AGE_MONTHS} months (20 years); this age is {} months.",
            fmt_num(age_months, 1)
        ));
    }
    for (name, v) in [
        ("height", opts.height),
        ("weight", opts.weight),
        ("head_circumference", opts.head_circumference),
    ] {
        if !v.is_finite() || v < 0.0 {
            return Err(format!(
                "{name} must be zero or more (use 0 when that measurement was not taken)."
            ));
        }
    }
    if opts.height <= 0.0 && opts.weight <= 0.0 && opts.head_circumference <= 0.0 {
        return Err(
            "Give at least one measurement: height, weight or head_circumference (0 means not measured)."
                .into(),
        );
    }

    let chart = opts.chart.resolve(age_months)?;
    let height_cm = units.to_cm(opts.height);
    let weight_kg = units.to_kg(opts.weight);
    let head_cm = units.to_cm(opts.head_circumference);

    let mut out = String::new();
    out.push_str("Child growth percentiles - CDC growth charts\n");
    out.push_str(&format!(
        "Child: {}, age {} ({} months)\n",
        sex.label(),
        fmt_age(age_months),
        fmt_num(age_months, 2)
    ));
    out.push_str(&format!("Reference: {}\n", chart.label()));

    let length_label = if chart == Chart::Infant {
        "Length-for-age"
    } else {
        "Height-for-age"
    };
    let mut lines: Vec<String> = Vec::new();
    let mut notes: Vec<String> = Vec::new();

    // --- length / stature for age ---
    if opts.height > 0.0 {
        let table = if chart == Chart::Infant {
            pick(
                sex,
                &tables::LENGTH_FOR_AGE_INFANT_BOY,
                &tables::LENGTH_FOR_AGE_INFANT_GIRL,
            )
        } else {
            pick(
                sex,
                &tables::STATURE_FOR_AGE_CHILD_BOY,
                &tables::STATURE_FOR_AGE_CHILD_GIRL,
            )
        };
        match z_score(table, age_months, height_cm) {
            Some(z) => lines.push(format!(
                "{length_label}: {} {} -> {}th percentile (z = {})",
                fmt_num(opts.height, 2),
                units.length_unit(),
                fmt_percentile(norm_cdf(z) * 100.0, decimals),
                fmt_num(z, decimals)
            )),
            None => notes.push(format!(
                "{length_label}: not available - this reference covers {} to {} months.",
                fmt_num(table_range(table).0, 1),
                fmt_num(table_range(table).1, 1)
            )),
        }
    }

    // --- weight for age ---
    if opts.weight > 0.0 {
        let table = if chart == Chart::Infant {
            pick(
                sex,
                &tables::WEIGHT_FOR_AGE_INFANT_BOY,
                &tables::WEIGHT_FOR_AGE_INFANT_GIRL,
            )
        } else {
            pick(
                sex,
                &tables::WEIGHT_FOR_AGE_CHILD_BOY,
                &tables::WEIGHT_FOR_AGE_CHILD_GIRL,
            )
        };
        match z_score(table, age_months, weight_kg) {
            Some(z) => lines.push(format!(
                "Weight-for-age: {} {} -> {}th percentile (z = {})",
                fmt_num(opts.weight, 2),
                units.mass_unit(),
                fmt_percentile(norm_cdf(z) * 100.0, decimals),
                fmt_num(z, decimals)
            )),
            None => notes.push(format!(
                "Weight-for-age: not available - this reference covers {} to {} months.",
                fmt_num(table_range(table).0, 1),
                fmt_num(table_range(table).1, 1)
            )),
        }
    }

    // --- BMI for age (2-20 years only) ---
    let mut category: Option<String> = None;
    if opts.height > 0.0 && opts.weight > 0.0 {
        let bmi = weight_kg / (height_cm / 100.0).powi(2);
        if age_months >= CHILD_CHART_START_MONTHS && chart == Chart::Child {
            let table = pick(
                sex,
                &tables::BMI_FOR_AGE_CHILD_BOY,
                &tables::BMI_FOR_AGE_CHILD_GIRL,
            );
            match z_score(table, age_months, bmi) {
                Some(z) => {
                    let percentile = norm_cdf(z) * 100.0;
                    lines.push(format!(
                        "BMI-for-age: {} kg/m2 -> {}th percentile (z = {})",
                        fmt_num(bmi, 2),
                        fmt_percentile(percentile, decimals),
                        fmt_num(z, decimals)
                    ));
                    if let Some(p95) = value_at_z(table, age_months, Z_AT_P95) {
                        category = Some(bmi_category(percentile, bmi, p95));
                    }
                }
                None => notes.push(format!(
                    "BMI-for-age: not available - BMI {} kg/m2 falls outside the reference.",
                    fmt_num(bmi, 2)
                )),
            }
        } else {
            notes.push(format!(
                "BMI-for-age: not available - CDC BMI-for-age starts at 24 months. BMI is {} kg/m2.",
                fmt_num(bmi, 2)
            ));
        }
    }

    // --- head circumference for age (birth to 36 months) ---
    if opts.head_circumference > 0.0 {
        let table = pick(
            sex,
            &tables::HEAD_FOR_AGE_INFANT_BOY,
            &tables::HEAD_FOR_AGE_INFANT_GIRL,
        );
        match z_score(table, age_months, head_cm) {
            Some(z) => lines.push(format!(
                "Head-circumference-for-age: {} {} -> {}th percentile (z = {})",
                fmt_num(opts.head_circumference, 2),
                units.length_unit(),
                fmt_percentile(norm_cdf(z) * 100.0, decimals),
                fmt_num(z, decimals)
            )),
            None => notes.push(format!(
                "Head-circumference-for-age: not available - the CDC head-circumference chart stops at {} months.",
                fmt_num(table_range(table).1, 1)
            )),
        }
    }

    // --- weight for length / weight for stature ---
    if opts.height > 0.0 && opts.weight > 0.0 {
        let (table, label) = if chart == Chart::Infant {
            (
                pick(
                    sex,
                    &tables::WEIGHT_FOR_LENGTH_BOY,
                    &tables::WEIGHT_FOR_LENGTH_GIRL,
                ),
                "Weight-for-length",
            )
        } else {
            (
                pick(
                    sex,
                    &tables::WEIGHT_FOR_STATURE_BOY,
                    &tables::WEIGHT_FOR_STATURE_GIRL,
                ),
                "Weight-for-stature",
            )
        };
        match z_score(table, height_cm, weight_kg) {
            Some(z) => lines.push(format!(
                "{label}: {} {} at {} cm -> {}th percentile (z = {})",
                fmt_num(opts.weight, 2),
                units.mass_unit(),
                fmt_num(height_cm, 1),
                fmt_percentile(norm_cdf(z) * 100.0, decimals),
                fmt_num(z, decimals)
            )),
            None => {
                let (lo, hi) = table_range(table);
                notes.push(format!(
                    "{label}: not available - that chart covers {} to {} cm.",
                    fmt_num(lo, 1),
                    fmt_num(hi, 1)
                ))
            }
        }
    }

    if lines.is_empty() && notes.is_empty() {
        return Err(
            "Nothing to report: no measurement matched a CDC reference for this age.".into(),
        );
    }

    out.push('\n');
    for line in &lines {
        out.push_str(line);
        out.push('\n');
    }
    if let Some(cat) = category {
        out.push_str(&format!("\nBMI category: {cat}\n"));
    }
    if !notes.is_empty() {
        out.push('\n');
        for note in &notes {
            out.push_str(note);
            out.push('\n');
        }
    }
    out.push_str(
        "\nPercentiles are a screening reference, not a diagnosis. Growth is judged over time and with clinical context - talk to a paediatric clinician about any concern.\n",
    );
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn base() -> Options {
        Options {
            sex: Sex::Girl,
            age_months: 36.0,
            height: 95.0,
            weight: 14.0,
            head_circumference: 0.0,
            units: Units::Metric,
            chart: Chart::Auto,
            decimals: 2,
        }
    }

    #[test]
    fn reports_height_weight_and_bmi_for_a_three_year_old_girl() {
        let out = report(&base()).unwrap();
        assert!(
            out.contains("Child: girl, age 3 y 0 mo (36 months)"),
            "{out}"
        );
        assert!(out.contains("Height-for-age: 95 cm -> "), "{out}");
        assert!(out.contains("Weight-for-age: 14 kg -> "), "{out}");
        assert!(out.contains("BMI-for-age: 15.51 kg/m2 -> "), "{out}");
        assert!(out.contains("BMI category: Healthy weight"), "{out}");
    }

    #[test]
    fn median_measurement_lands_on_the_fiftieth_percentile() {
        // CDC stature-for-age, girls, 36 months: linearly interpolated M between
        // the 35.5 and 36.5 month rows, so the median girl is ~50th.
        let mut o = base();
        o.weight = 0.0;
        o.height = 93.923589935;
        let out = report(&o).unwrap();
        assert!(
            out.contains("Height-for-age: 93.92 cm -> 50th percentile (z = 0)"),
            "{out}"
        );
    }

    #[test]
    fn newborn_uses_the_infant_charts_and_head_circumference() {
        let mut o = base();
        o.sex = Sex::Boy;
        o.age_months = 0.0;
        o.height = 49.98888408; // the CDC median length for a newborn boy
        o.weight = 3.53;
        o.head_circumference = 35.81366835;
        let out = report(&o).unwrap();
        assert!(out.contains("CDC infant growth charts"), "{out}");
        assert!(
            out.contains("Length-for-age: 49.99 cm -> 50th percentile (z = 0)"),
            "{out}"
        );
        assert!(
            out.contains("Head-circumference-for-age: 35.81 in") == false,
            "{out}"
        );
        assert!(
            out.contains("Head-circumference-for-age: 35.81 cm -> 50th percentile"),
            "{out}"
        );
        assert!(out.contains("Weight-for-length"), "{out}");
        assert!(out.contains("BMI-for-age: not available"), "{out}");
    }

    #[test]
    fn us_units_convert_to_metric_before_the_lookup() {
        let mut o = base();
        o.units = Units::Us;
        o.height = 95.0 / CM_PER_INCH;
        o.weight = 14.0 / KG_PER_POUND;
        let out = report(&o).unwrap();
        assert!(
            out.contains("-> 15.6th percentile") || out.contains("in -> "),
            "{out}"
        );
        assert!(out.contains("BMI-for-age: 15.51 kg/m2"), "{out}");
    }

    #[test]
    fn parse_age_accepts_months_years_and_date_ranges() {
        assert_eq!(parse_age("36").unwrap(), 36.0);
        assert_eq!(parse_age("3y").unwrap(), 36.0);
        assert_eq!(parse_age("3y 4m").unwrap(), 40.0);
        assert_eq!(parse_age("18 months").unwrap(), 18.0);
        assert_eq!(parse_age("2.5 years").unwrap(), 30.0);
        assert!((parse_age("6 weeks").unwrap() - 42.0 / DAYS_PER_MONTH).abs() < 1e-9);
        // 2023-04-15 -> 2026-08-23 is 1226 days.
        let months = parse_age("2023-04-15 to 2026-08-23").unwrap();
        assert!((months - 1226.0 / DAYS_PER_MONTH).abs() < 1e-9, "{months}");
        assert_eq!(parse_age("2023-04-15..2023-04-15").unwrap(), 0.0);
    }

    #[test]
    fn parse_age_rejects_an_unknown_unit() {
        let err = parse_age("3 fortnights").unwrap_err();
        assert!(err.contains("Unknown age unit"), "{err}");
    }

    #[test]
    fn report_rejects_an_age_past_twenty_years() {
        let mut o = base();
        o.age_months = 241.0;
        let err = report(&o).unwrap_err();
        assert!(err.contains("stop at 240 months"), "{err}");
    }

    #[test]
    fn report_rejects_a_run_with_no_measurements() {
        let mut o = base();
        o.height = 0.0;
        o.weight = 0.0;
        let err = report(&o).unwrap_err();
        assert!(err.contains("at least one measurement"), "{err}");
    }

    #[test]
    fn chart_child_rejects_an_infant_age() {
        let mut o = base();
        o.age_months = 6.0;
        o.chart = Chart::Child;
        let err = report(&o).unwrap_err();
        assert!(err.contains("chart=child starts at 24 months"), "{err}");
    }

    #[test]
    fn sex_and_units_reject_garbage() {
        assert!(Sex::parse("robot").unwrap_err().contains("Unknown sex"));
        assert!(Units::parse("stones")
            .unwrap_err()
            .contains("Unknown units"));
        assert!(Chart::parse("who").unwrap_err().contains("Unknown chart"));
        assert!(decimals_from(9).unwrap_err().contains("between 0 and 4"));
    }

    #[test]
    fn norm_cdf_matches_known_quantiles() {
        assert!((norm_cdf(0.0) - 0.5).abs() < 1e-12);
        assert!((norm_cdf(Z_AT_P95) - 0.95).abs() < 1e-10);
        assert!((norm_cdf(-1.959963984540054) - 0.025).abs() < 1e-10);
        assert!((norm_cdf(3.0) - 0.998650101968370).abs() < 1e-12);
    }

    #[test]
    fn every_table_is_sorted_and_non_empty() {
        let all: [&[Lms]; 16] = [
            &tables::LENGTH_FOR_AGE_INFANT_BOY,
            &tables::LENGTH_FOR_AGE_INFANT_GIRL,
            &tables::WEIGHT_FOR_AGE_INFANT_BOY,
            &tables::WEIGHT_FOR_AGE_INFANT_GIRL,
            &tables::HEAD_FOR_AGE_INFANT_BOY,
            &tables::HEAD_FOR_AGE_INFANT_GIRL,
            &tables::WEIGHT_FOR_LENGTH_BOY,
            &tables::WEIGHT_FOR_LENGTH_GIRL,
            &tables::STATURE_FOR_AGE_CHILD_BOY,
            &tables::STATURE_FOR_AGE_CHILD_GIRL,
            &tables::WEIGHT_FOR_AGE_CHILD_BOY,
            &tables::WEIGHT_FOR_AGE_CHILD_GIRL,
            &tables::BMI_FOR_AGE_CHILD_BOY,
            &tables::BMI_FOR_AGE_CHILD_GIRL,
            &tables::WEIGHT_FOR_STATURE_BOY,
            &tables::WEIGHT_FOR_STATURE_GIRL,
        ];
        for t in all {
            assert!(!t.is_empty());
            assert!(t.windows(2).all(|w| w[0].0 < w[1].0), "table not sorted");
            assert!(t.iter().all(|r| r.2 > 0.0 && r.3 > 0.0), "bad M or S");
        }
    }

    #[test]
    fn severe_obesity_is_flagged_above_120_percent_of_p95() {
        let mut o = base();
        o.age_months = 120.0;
        o.height = 140.0;
        o.weight = 70.0;
        let out = report(&o).unwrap();
        assert!(out.contains("BMI category: Severe obesity"), "{out}");
    }
}
