use std::{env, fs, path::PathBuf};
fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let blocks_dir = PathBuf::from(&manifest_dir).parent().unwrap().join("blocks");
    let mut wasm_paths: Vec<PathBuf> = Vec::new();
    if blocks_dir.is_dir() {
        for entry in fs::read_dir(&blocks_dir).expect("read blocks/") {
            let wasm = entry.expect("entry").path().join("target/block.wasm");
            if wasm.is_file() {
                println!("cargo:rerun-if-changed={}", wasm.display());
                wasm_paths.push(wasm);
            }
        }
    }
    wasm_paths.sort();
    if wasm_paths.is_empty() {
        println!("cargo:warning=no blocks/*/target/block.wasm found — run `solobase build` first; the CLI will have zero tools");
    }
    println!("cargo:rerun-if-changed={}", blocks_dir.display());
    let mut out = String::from("// Generated by build.rs — do not edit.\n");
    out.push_str("pub const SKILL_WASMS: &[&[u8]] = &[\n");
    for p in &wasm_paths {
        out.push_str(&format!("    include_bytes!(\"{}\"),\n", p.to_string_lossy().replace('\\', "/")));
    }
    out.push_str("];\n");
    fs::write(PathBuf::from(&out_dir).join("skill_wasms.rs"), out).expect("write skill_wasms.rs");
}
