[package]
name = "gizza-ai-gost-kuznyechik-cipher-core"
version = "0.1.0"
edition = "2021"
rust-version = "1.82"

[dependencies]
kuznyechik = "0.8"
cbc = { version = "0.1", features = ["alloc"] }
ctr = "0.9"
cfb-mode = "0.8"
ofb = "0.6"
ecb = { version = "0.1", features = ["alloc"] }
cipher = { version = "0.4", features = ["block-padding", "alloc"] }
hex = "0.4"
base64 = "0.22"
